// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface DeleteS3FileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.DeleteS3FileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * S3 object key (path after domain)
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * S3 object key (path after domain)
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
