// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

/**
 * Protobuf type {@code recorder.FetchGameProvideListResponse}
 */
public final class FetchGameProvideListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder.FetchGameProvideListResponse)
    FetchGameProvideListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      FetchGameProvideListResponse.class.getName());
  }
  // Use FetchGameProvideListResponse.newBuilder() to construct.
  private FetchGameProvideListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FetchGameProvideListResponse() {
    gameProvides_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_FetchGameProvideListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_FetchGameProvideListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wecasino.proto.recorder.FetchGameProvideListResponse.class, com.wecasino.proto.recorder.FetchGameProvideListResponse.Builder.class);
  }

  public static final int GAME_PROVIDES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.wecasino.proto.recorder.GameProvide> gameProvides_;
  /**
   * <pre>
   * 桌列表
   * </pre>
   *
   * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
   */
  @java.lang.Override
  public java.util.List<com.wecasino.proto.recorder.GameProvide> getGameProvidesList() {
    return gameProvides_;
  }
  /**
   * <pre>
   * 桌列表
   * </pre>
   *
   * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wecasino.proto.recorder.GameProvideOrBuilder> 
      getGameProvidesOrBuilderList() {
    return gameProvides_;
  }
  /**
   * <pre>
   * 桌列表
   * </pre>
   *
   * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
   */
  @java.lang.Override
  public int getGameProvidesCount() {
    return gameProvides_.size();
  }
  /**
   * <pre>
   * 桌列表
   * </pre>
   *
   * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
   */
  @java.lang.Override
  public com.wecasino.proto.recorder.GameProvide getGameProvides(int index) {
    return gameProvides_.get(index);
  }
  /**
   * <pre>
   * 桌列表
   * </pre>
   *
   * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
   */
  @java.lang.Override
  public com.wecasino.proto.recorder.GameProvideOrBuilder getGameProvidesOrBuilder(
      int index) {
    return gameProvides_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < gameProvides_.size(); i++) {
      output.writeMessage(1, gameProvides_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < gameProvides_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, gameProvides_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wecasino.proto.recorder.FetchGameProvideListResponse)) {
      return super.equals(obj);
    }
    com.wecasino.proto.recorder.FetchGameProvideListResponse other = (com.wecasino.proto.recorder.FetchGameProvideListResponse) obj;

    if (!getGameProvidesList()
        .equals(other.getGameProvidesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGameProvidesCount() > 0) {
      hash = (37 * hash) + GAME_PROVIDES_FIELD_NUMBER;
      hash = (53 * hash) + getGameProvidesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.FetchGameProvideListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wecasino.proto.recorder.FetchGameProvideListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder.FetchGameProvideListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder.FetchGameProvideListResponse)
      com.wecasino.proto.recorder.FetchGameProvideListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_FetchGameProvideListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_FetchGameProvideListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wecasino.proto.recorder.FetchGameProvideListResponse.class, com.wecasino.proto.recorder.FetchGameProvideListResponse.Builder.class);
    }

    // Construct using com.wecasino.proto.recorder.FetchGameProvideListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (gameProvidesBuilder_ == null) {
        gameProvides_ = java.util.Collections.emptyList();
      } else {
        gameProvides_ = null;
        gameProvidesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_FetchGameProvideListResponse_descriptor;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.FetchGameProvideListResponse getDefaultInstanceForType() {
      return com.wecasino.proto.recorder.FetchGameProvideListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.FetchGameProvideListResponse build() {
      com.wecasino.proto.recorder.FetchGameProvideListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.FetchGameProvideListResponse buildPartial() {
      com.wecasino.proto.recorder.FetchGameProvideListResponse result = new com.wecasino.proto.recorder.FetchGameProvideListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.wecasino.proto.recorder.FetchGameProvideListResponse result) {
      if (gameProvidesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          gameProvides_ = java.util.Collections.unmodifiableList(gameProvides_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.gameProvides_ = gameProvides_;
      } else {
        result.gameProvides_ = gameProvidesBuilder_.build();
      }
    }

    private void buildPartial0(com.wecasino.proto.recorder.FetchGameProvideListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wecasino.proto.recorder.FetchGameProvideListResponse) {
        return mergeFrom((com.wecasino.proto.recorder.FetchGameProvideListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wecasino.proto.recorder.FetchGameProvideListResponse other) {
      if (other == com.wecasino.proto.recorder.FetchGameProvideListResponse.getDefaultInstance()) return this;
      if (gameProvidesBuilder_ == null) {
        if (!other.gameProvides_.isEmpty()) {
          if (gameProvides_.isEmpty()) {
            gameProvides_ = other.gameProvides_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGameProvidesIsMutable();
            gameProvides_.addAll(other.gameProvides_);
          }
          onChanged();
        }
      } else {
        if (!other.gameProvides_.isEmpty()) {
          if (gameProvidesBuilder_.isEmpty()) {
            gameProvidesBuilder_.dispose();
            gameProvidesBuilder_ = null;
            gameProvides_ = other.gameProvides_;
            bitField0_ = (bitField0_ & ~0x00000001);
            gameProvidesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGameProvidesFieldBuilder() : null;
          } else {
            gameProvidesBuilder_.addAllMessages(other.gameProvides_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.wecasino.proto.recorder.GameProvide m =
                  input.readMessage(
                      com.wecasino.proto.recorder.GameProvide.parser(),
                      extensionRegistry);
              if (gameProvidesBuilder_ == null) {
                ensureGameProvidesIsMutable();
                gameProvides_.add(m);
              } else {
                gameProvidesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wecasino.proto.recorder.GameProvide> gameProvides_ =
      java.util.Collections.emptyList();
    private void ensureGameProvidesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        gameProvides_ = new java.util.ArrayList<com.wecasino.proto.recorder.GameProvide>(gameProvides_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.wecasino.proto.recorder.GameProvide, com.wecasino.proto.recorder.GameProvide.Builder, com.wecasino.proto.recorder.GameProvideOrBuilder> gameProvidesBuilder_;

    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public java.util.List<com.wecasino.proto.recorder.GameProvide> getGameProvidesList() {
      if (gameProvidesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(gameProvides_);
      } else {
        return gameProvidesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public int getGameProvidesCount() {
      if (gameProvidesBuilder_ == null) {
        return gameProvides_.size();
      } else {
        return gameProvidesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public com.wecasino.proto.recorder.GameProvide getGameProvides(int index) {
      if (gameProvidesBuilder_ == null) {
        return gameProvides_.get(index);
      } else {
        return gameProvidesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder setGameProvides(
        int index, com.wecasino.proto.recorder.GameProvide value) {
      if (gameProvidesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameProvidesIsMutable();
        gameProvides_.set(index, value);
        onChanged();
      } else {
        gameProvidesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder setGameProvides(
        int index, com.wecasino.proto.recorder.GameProvide.Builder builderForValue) {
      if (gameProvidesBuilder_ == null) {
        ensureGameProvidesIsMutable();
        gameProvides_.set(index, builderForValue.build());
        onChanged();
      } else {
        gameProvidesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder addGameProvides(com.wecasino.proto.recorder.GameProvide value) {
      if (gameProvidesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameProvidesIsMutable();
        gameProvides_.add(value);
        onChanged();
      } else {
        gameProvidesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder addGameProvides(
        int index, com.wecasino.proto.recorder.GameProvide value) {
      if (gameProvidesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameProvidesIsMutable();
        gameProvides_.add(index, value);
        onChanged();
      } else {
        gameProvidesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder addGameProvides(
        com.wecasino.proto.recorder.GameProvide.Builder builderForValue) {
      if (gameProvidesBuilder_ == null) {
        ensureGameProvidesIsMutable();
        gameProvides_.add(builderForValue.build());
        onChanged();
      } else {
        gameProvidesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder addGameProvides(
        int index, com.wecasino.proto.recorder.GameProvide.Builder builderForValue) {
      if (gameProvidesBuilder_ == null) {
        ensureGameProvidesIsMutable();
        gameProvides_.add(index, builderForValue.build());
        onChanged();
      } else {
        gameProvidesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder addAllGameProvides(
        java.lang.Iterable<? extends com.wecasino.proto.recorder.GameProvide> values) {
      if (gameProvidesBuilder_ == null) {
        ensureGameProvidesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gameProvides_);
        onChanged();
      } else {
        gameProvidesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder clearGameProvides() {
      if (gameProvidesBuilder_ == null) {
        gameProvides_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        gameProvidesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public Builder removeGameProvides(int index) {
      if (gameProvidesBuilder_ == null) {
        ensureGameProvidesIsMutable();
        gameProvides_.remove(index);
        onChanged();
      } else {
        gameProvidesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public com.wecasino.proto.recorder.GameProvide.Builder getGameProvidesBuilder(
        int index) {
      return getGameProvidesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public com.wecasino.proto.recorder.GameProvideOrBuilder getGameProvidesOrBuilder(
        int index) {
      if (gameProvidesBuilder_ == null) {
        return gameProvides_.get(index);  } else {
        return gameProvidesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public java.util.List<? extends com.wecasino.proto.recorder.GameProvideOrBuilder> 
         getGameProvidesOrBuilderList() {
      if (gameProvidesBuilder_ != null) {
        return gameProvidesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(gameProvides_);
      }
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public com.wecasino.proto.recorder.GameProvide.Builder addGameProvidesBuilder() {
      return getGameProvidesFieldBuilder().addBuilder(
          com.wecasino.proto.recorder.GameProvide.getDefaultInstance());
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public com.wecasino.proto.recorder.GameProvide.Builder addGameProvidesBuilder(
        int index) {
      return getGameProvidesFieldBuilder().addBuilder(
          index, com.wecasino.proto.recorder.GameProvide.getDefaultInstance());
    }
    /**
     * <pre>
     * 桌列表
     * </pre>
     *
     * <code>repeated .recorder.GameProvide game_provides = 1 [json_name = "gameProvides"];</code>
     */
    public java.util.List<com.wecasino.proto.recorder.GameProvide.Builder> 
         getGameProvidesBuilderList() {
      return getGameProvidesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.wecasino.proto.recorder.GameProvide, com.wecasino.proto.recorder.GameProvide.Builder, com.wecasino.proto.recorder.GameProvideOrBuilder> 
        getGameProvidesFieldBuilder() {
      if (gameProvidesBuilder_ == null) {
        gameProvidesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.wecasino.proto.recorder.GameProvide, com.wecasino.proto.recorder.GameProvide.Builder, com.wecasino.proto.recorder.GameProvideOrBuilder>(
                gameProvides_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        gameProvides_ = null;
      }
      return gameProvidesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:recorder.FetchGameProvideListResponse)
  }

  // @@protoc_insertion_point(class_scope:recorder.FetchGameProvideListResponse)
  private static final com.wecasino.proto.recorder.FetchGameProvideListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wecasino.proto.recorder.FetchGameProvideListResponse();
  }

  public static com.wecasino.proto.recorder.FetchGameProvideListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchGameProvideListResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchGameProvideListResponse>() {
    @java.lang.Override
    public FetchGameProvideListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchGameProvideListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchGameProvideListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wecasino.proto.recorder.FetchGameProvideListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

