// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

public interface FetchCurrentGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.FetchCurrentGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 查詢的遊戲代號
   * </pre>
   *
   * <code>repeated string game_codes = 1 [json_name = "gameCodes"];</code>
   * @return A list containing the gameCodes.
   */
  java.util.List<java.lang.String>
      getGameCodesList();
  /**
   * <pre>
   * 查詢的遊戲代號
   * </pre>
   *
   * <code>repeated string game_codes = 1 [json_name = "gameCodes"];</code>
   * @return The count of gameCodes.
   */
  int getGameCodesCount();
  /**
   * <pre>
   * 查詢的遊戲代號
   * </pre>
   *
   * <code>repeated string game_codes = 1 [json_name = "gameCodes"];</code>
   * @param index The index of the element to return.
   * @return The gameCodes at the given index.
   */
  java.lang.String getGameCodes(int index);
  /**
   * <pre>
   * 查詢的遊戲代號
   * </pre>
   *
   * <code>repeated string game_codes = 1 [json_name = "gameCodes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the gameCodes at the given index.
   */
  com.google.protobuf.ByteString
      getGameCodesBytes(int index);

  /**
   * <pre>
   * 返回班表資訊
   * </pre>
   *
   * <code>bool shift = 8 [json_name = "shift"];</code>
   * @return The shift.
   */
  boolean getShift();

  /**
   * <pre>
   * 返回牌靴資訊
   * </pre>
   *
   * <code>bool shoe = 10 [json_name = "shoe"];</code>
   * @return The shoe.
   */
  boolean getShoe();
}
