// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

public interface FetchGameProvideListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.FetchGameProvideListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 平台
   * </pre>
   *
   * <code>string platform = 1 [json_name = "platform"];</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <pre>
   * 平台
   * </pre>
   *
   * <code>string platform = 1 [json_name = "platform"];</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();
}
