// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

/**
 * Protobuf type {@code recorder.InputLuckyRecordRequest}
 */
public final class InputLuckyRecordRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recorder.InputLuckyRecordRequest)
    InputLuckyRecordRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InputLuckyRecordRequest.newBuilder() to construct.
  private InputLuckyRecordRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InputLuckyRecordRequest() {
    gameType_ = "";
    gameCode_ = "";
    roundShoe_ = "";
    roundCode_ = "";
    roundLucky_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InputLuckyRecordRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_InputLuckyRecordRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_InputLuckyRecordRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wecasino.proto.recorder.InputLuckyRecordRequest.class, com.wecasino.proto.recorder.InputLuckyRecordRequest.Builder.class);
  }

  public static final int GAME_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameType_ = "";
  /**
   * <code>string game_type = 1 [json_name = "gameType"];</code>
   * @return The gameType.
   */
  @java.lang.Override
  public java.lang.String getGameType() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameType_ = s;
      return s;
    }
  }
  /**
   * <code>string game_type = 1 [json_name = "gameType"];</code>
   * @return The bytes for gameType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameTypeBytes() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_CODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameCode_ = "";
  /**
   * <code>string game_code = 2 [json_name = "gameCode"];</code>
   * @return The gameCode.
   */
  @java.lang.Override
  public java.lang.String getGameCode() {
    java.lang.Object ref = gameCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameCode_ = s;
      return s;
    }
  }
  /**
   * <code>string game_code = 2 [json_name = "gameCode"];</code>
   * @return The bytes for gameCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameCodeBytes() {
    java.lang.Object ref = gameCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUND_SHOE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roundShoe_ = "";
  /**
   * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
   * @return The roundShoe.
   */
  @java.lang.Override
  public java.lang.String getRoundShoe() {
    java.lang.Object ref = roundShoe_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roundShoe_ = s;
      return s;
    }
  }
  /**
   * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
   * @return The bytes for roundShoe.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoundShoeBytes() {
    java.lang.Object ref = roundShoe_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roundShoe_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUND_CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roundCode_ = "";
  /**
   * <code>string round_code = 4 [json_name = "roundCode"];</code>
   * @return The roundCode.
   */
  @java.lang.Override
  public java.lang.String getRoundCode() {
    java.lang.Object ref = roundCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roundCode_ = s;
      return s;
    }
  }
  /**
   * <code>string round_code = 4 [json_name = "roundCode"];</code>
   * @return The bytes for roundCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoundCodeBytes() {
    java.lang.Object ref = roundCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roundCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUND_LUCKY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roundLucky_ = "";
  /**
   * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
   * @return The roundLucky.
   */
  @java.lang.Override
  public java.lang.String getRoundLucky() {
    java.lang.Object ref = roundLucky_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roundLucky_ = s;
      return s;
    }
  }
  /**
   * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
   * @return The bytes for roundLucky.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoundLuckyBytes() {
    java.lang.Object ref = roundLucky_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roundLucky_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gameType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gameType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gameCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gameCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundShoe_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roundShoe_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, roundCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundLucky_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roundLucky_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gameType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gameType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gameCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gameCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundShoe_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roundShoe_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, roundCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roundLucky_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roundLucky_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wecasino.proto.recorder.InputLuckyRecordRequest)) {
      return super.equals(obj);
    }
    com.wecasino.proto.recorder.InputLuckyRecordRequest other = (com.wecasino.proto.recorder.InputLuckyRecordRequest) obj;

    if (!getGameType()
        .equals(other.getGameType())) return false;
    if (!getGameCode()
        .equals(other.getGameCode())) return false;
    if (!getRoundShoe()
        .equals(other.getRoundShoe())) return false;
    if (!getRoundCode()
        .equals(other.getRoundCode())) return false;
    if (!getRoundLucky()
        .equals(other.getRoundLucky())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GAME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGameType().hashCode();
    hash = (37 * hash) + GAME_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getGameCode().hashCode();
    hash = (37 * hash) + ROUND_SHOE_FIELD_NUMBER;
    hash = (53 * hash) + getRoundShoe().hashCode();
    hash = (37 * hash) + ROUND_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoundCode().hashCode();
    hash = (37 * hash) + ROUND_LUCKY_FIELD_NUMBER;
    hash = (53 * hash) + getRoundLucky().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.InputLuckyRecordRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wecasino.proto.recorder.InputLuckyRecordRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder.InputLuckyRecordRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder.InputLuckyRecordRequest)
      com.wecasino.proto.recorder.InputLuckyRecordRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_InputLuckyRecordRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_InputLuckyRecordRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wecasino.proto.recorder.InputLuckyRecordRequest.class, com.wecasino.proto.recorder.InputLuckyRecordRequest.Builder.class);
    }

    // Construct using com.wecasino.proto.recorder.InputLuckyRecordRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gameType_ = "";
      gameCode_ = "";
      roundShoe_ = "";
      roundCode_ = "";
      roundLucky_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wecasino.proto.recorder.ProviderProto.internal_static_recorder_InputLuckyRecordRequest_descriptor;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.InputLuckyRecordRequest getDefaultInstanceForType() {
      return com.wecasino.proto.recorder.InputLuckyRecordRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.InputLuckyRecordRequest build() {
      com.wecasino.proto.recorder.InputLuckyRecordRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.InputLuckyRecordRequest buildPartial() {
      com.wecasino.proto.recorder.InputLuckyRecordRequest result = new com.wecasino.proto.recorder.InputLuckyRecordRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.wecasino.proto.recorder.InputLuckyRecordRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gameType_ = gameType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gameCode_ = gameCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.roundShoe_ = roundShoe_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.roundCode_ = roundCode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.roundLucky_ = roundLucky_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wecasino.proto.recorder.InputLuckyRecordRequest) {
        return mergeFrom((com.wecasino.proto.recorder.InputLuckyRecordRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wecasino.proto.recorder.InputLuckyRecordRequest other) {
      if (other == com.wecasino.proto.recorder.InputLuckyRecordRequest.getDefaultInstance()) return this;
      if (!other.getGameType().isEmpty()) {
        gameType_ = other.gameType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGameCode().isEmpty()) {
        gameCode_ = other.gameCode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRoundShoe().isEmpty()) {
        roundShoe_ = other.roundShoe_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRoundCode().isEmpty()) {
        roundCode_ = other.roundCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getRoundLucky().isEmpty()) {
        roundLucky_ = other.roundLucky_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gameType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              gameCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              roundShoe_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              roundCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              roundLucky_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object gameType_ = "";
    /**
     * <code>string game_type = 1 [json_name = "gameType"];</code>
     * @return The gameType.
     */
    public java.lang.String getGameType() {
      java.lang.Object ref = gameType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string game_type = 1 [json_name = "gameType"];</code>
     * @return The bytes for gameType.
     */
    public com.google.protobuf.ByteString
        getGameTypeBytes() {
      java.lang.Object ref = gameType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string game_type = 1 [json_name = "gameType"];</code>
     * @param value The gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string game_type = 1 [json_name = "gameType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameType() {
      gameType_ = getDefaultInstance().getGameType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string game_type = 1 [json_name = "gameType"];</code>
     * @param value The bytes for gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object gameCode_ = "";
    /**
     * <code>string game_code = 2 [json_name = "gameCode"];</code>
     * @return The gameCode.
     */
    public java.lang.String getGameCode() {
      java.lang.Object ref = gameCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string game_code = 2 [json_name = "gameCode"];</code>
     * @return The bytes for gameCode.
     */
    public com.google.protobuf.ByteString
        getGameCodeBytes() {
      java.lang.Object ref = gameCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string game_code = 2 [json_name = "gameCode"];</code>
     * @param value The gameCode to set.
     * @return This builder for chaining.
     */
    public Builder setGameCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string game_code = 2 [json_name = "gameCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameCode() {
      gameCode_ = getDefaultInstance().getGameCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string game_code = 2 [json_name = "gameCode"];</code>
     * @param value The bytes for gameCode to set.
     * @return This builder for chaining.
     */
    public Builder setGameCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object roundShoe_ = "";
    /**
     * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
     * @return The roundShoe.
     */
    public java.lang.String getRoundShoe() {
      java.lang.Object ref = roundShoe_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roundShoe_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
     * @return The bytes for roundShoe.
     */
    public com.google.protobuf.ByteString
        getRoundShoeBytes() {
      java.lang.Object ref = roundShoe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roundShoe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
     * @param value The roundShoe to set.
     * @return This builder for chaining.
     */
    public Builder setRoundShoe(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roundShoe_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundShoe() {
      roundShoe_ = getDefaultInstance().getRoundShoe();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
     * @param value The bytes for roundShoe to set.
     * @return This builder for chaining.
     */
    public Builder setRoundShoeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roundShoe_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object roundCode_ = "";
    /**
     * <code>string round_code = 4 [json_name = "roundCode"];</code>
     * @return The roundCode.
     */
    public java.lang.String getRoundCode() {
      java.lang.Object ref = roundCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roundCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string round_code = 4 [json_name = "roundCode"];</code>
     * @return The bytes for roundCode.
     */
    public com.google.protobuf.ByteString
        getRoundCodeBytes() {
      java.lang.Object ref = roundCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roundCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string round_code = 4 [json_name = "roundCode"];</code>
     * @param value The roundCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoundCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roundCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string round_code = 4 [json_name = "roundCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundCode() {
      roundCode_ = getDefaultInstance().getRoundCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string round_code = 4 [json_name = "roundCode"];</code>
     * @param value The bytes for roundCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoundCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roundCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object roundLucky_ = "";
    /**
     * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
     * @return The roundLucky.
     */
    public java.lang.String getRoundLucky() {
      java.lang.Object ref = roundLucky_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roundLucky_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
     * @return The bytes for roundLucky.
     */
    public com.google.protobuf.ByteString
        getRoundLuckyBytes() {
      java.lang.Object ref = roundLucky_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roundLucky_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
     * @param value The roundLucky to set.
     * @return This builder for chaining.
     */
    public Builder setRoundLucky(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roundLucky_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundLucky() {
      roundLucky_ = getDefaultInstance().getRoundLucky();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
     * @param value The bytes for roundLucky to set.
     * @return This builder for chaining.
     */
    public Builder setRoundLuckyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roundLucky_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recorder.InputLuckyRecordRequest)
  }

  // @@protoc_insertion_point(class_scope:recorder.InputLuckyRecordRequest)
  private static final com.wecasino.proto.recorder.InputLuckyRecordRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wecasino.proto.recorder.InputLuckyRecordRequest();
  }

  public static com.wecasino.proto.recorder.InputLuckyRecordRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InputLuckyRecordRequest>
      PARSER = new com.google.protobuf.AbstractParser<InputLuckyRecordRequest>() {
    @java.lang.Override
    public InputLuckyRecordRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InputLuckyRecordRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InputLuckyRecordRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wecasino.proto.recorder.InputLuckyRecordRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

