// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface InputLuckyRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.InputLuckyRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string game_type = 1 [json_name = "gameType"];</code>
   * @return The gameType.
   */
  java.lang.String getGameType();
  /**
   * <code>string game_type = 1 [json_name = "gameType"];</code>
   * @return The bytes for gameType.
   */
  com.google.protobuf.ByteString
      getGameTypeBytes();

  /**
   * <code>string game_code = 2 [json_name = "gameCode"];</code>
   * @return The gameCode.
   */
  java.lang.String getGameCode();
  /**
   * <code>string game_code = 2 [json_name = "gameCode"];</code>
   * @return The bytes for gameCode.
   */
  com.google.protobuf.ByteString
      getGameCodeBytes();

  /**
   * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
   * @return The roundShoe.
   */
  java.lang.String getRoundShoe();
  /**
   * <code>string round_shoe = 3 [json_name = "roundShoe"];</code>
   * @return The bytes for roundShoe.
   */
  com.google.protobuf.ByteString
      getRoundShoeBytes();

  /**
   * <code>string round_code = 4 [json_name = "roundCode"];</code>
   * @return The roundCode.
   */
  java.lang.String getRoundCode();
  /**
   * <code>string round_code = 4 [json_name = "roundCode"];</code>
   * @return The bytes for roundCode.
   */
  com.google.protobuf.ByteString
      getRoundCodeBytes();

  /**
   * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
   * @return The roundLucky.
   */
  java.lang.String getRoundLucky();
  /**
   * <code>string round_lucky = 5 [json_name = "roundLucky"];</code>
   * @return The bytes for roundLucky.
   */
  com.google.protobuf.ByteString
      getRoundLuckyBytes();
}
