// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface InputLuckyRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.InputLuckyRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
