// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface ListShoesRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.ListShoesRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * shoes
   * </pre>
   *
   * <code>repeated .recorder.ShoeRecord shoe_record = 1 [json_name = "shoeRecord"];</code>
   */
  java.util.List<com.wecasino.proto.recorder.ShoeRecord> 
      getShoeRecordList();
  /**
   * <pre>
   * shoes
   * </pre>
   *
   * <code>repeated .recorder.ShoeRecord shoe_record = 1 [json_name = "shoeRecord"];</code>
   */
  com.wecasino.proto.recorder.ShoeRecord getShoeRecord(int index);
  /**
   * <pre>
   * shoes
   * </pre>
   *
   * <code>repeated .recorder.ShoeRecord shoe_record = 1 [json_name = "shoeRecord"];</code>
   */
  int getShoeRecordCount();
  /**
   * <pre>
   * shoes
   * </pre>
   *
   * <code>repeated .recorder.ShoeRecord shoe_record = 1 [json_name = "shoeRecord"];</code>
   */
  java.util.List<? extends com.wecasino.proto.recorder.ShoeRecordOrBuilder> 
      getShoeRecordOrBuilderList();
  /**
   * <pre>
   * shoes
   * </pre>
   *
   * <code>repeated .recorder.ShoeRecord shoe_record = 1 [json_name = "shoeRecord"];</code>
   */
  com.wecasino.proto.recorder.ShoeRecordOrBuilder getShoeRecordOrBuilder(
      int index);

  /**
   * <pre>
   * 總數
   * </pre>
   *
   * <code>int64 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <pre>
   * pagination next page
   * </pre>
   *
   * <code>string search_after = 8 [json_name = "searchAfter"];</code>
   * @return The searchAfter.
   */
  java.lang.String getSearchAfter();
  /**
   * <pre>
   * pagination next page
   * </pre>
   *
   * <code>string search_after = 8 [json_name = "searchAfter"];</code>
   * @return The bytes for searchAfter.
   */
  com.google.protobuf.ByteString
      getSearchAfterBytes();

  /**
   * <pre>
   * pagination previous page
   * </pre>
   *
   * <code>string search_before = 9 [json_name = "searchBefore"];</code>
   * @return The searchBefore.
   */
  java.lang.String getSearchBefore();
  /**
   * <pre>
   * pagination previous page
   * </pre>
   *
   * <code>string search_before = 9 [json_name = "searchBefore"];</code>
   * @return The bytes for searchBefore.
   */
  com.google.protobuf.ByteString
      getSearchBeforeBytes();
}
