// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface ListS3FoldersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.ListS3FoldersRequest)
    com.google.protobuf.MessageOrBuilder {
}
