// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface ListGamesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.ListGamesRequest)
    com.google.protobuf.MessageOrBuilder {
}
