// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface RecordRoundStepsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.RecordRoundStepsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 紀錄ID
   * </pre>
   *
   * <code>bytes record_id = 1 [json_name = "recordId"];</code>
   * @return The recordId.
   */
  com.google.protobuf.ByteString getRecordId();

  /**
   * <pre>
   * 步驟
   * </pre>
   *
   * <code>repeated .recorder.Step steps = 26 [json_name = "steps"];</code>
   */
  java.util.List<com.wecasino.proto.recorder.Step> 
      getStepsList();
  /**
   * <pre>
   * 步驟
   * </pre>
   *
   * <code>repeated .recorder.Step steps = 26 [json_name = "steps"];</code>
   */
  com.wecasino.proto.recorder.Step getSteps(int index);
  /**
   * <pre>
   * 步驟
   * </pre>
   *
   * <code>repeated .recorder.Step steps = 26 [json_name = "steps"];</code>
   */
  int getStepsCount();
  /**
   * <pre>
   * 步驟
   * </pre>
   *
   * <code>repeated .recorder.Step steps = 26 [json_name = "steps"];</code>
   */
  java.util.List<? extends com.wecasino.proto.recorder.StepOrBuilder> 
      getStepsOrBuilderList();
  /**
   * <pre>
   * 步驟
   * </pre>
   *
   * <code>repeated .recorder.Step steps = 26 [json_name = "steps"];</code>
   */
  com.wecasino.proto.recorder.StepOrBuilder getStepsOrBuilder(
      int index);
}
