// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public interface RecordIDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.RecordIDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 紀錄ID
   * </pre>
   *
   * <code>bytes record_id = 1 [json_name = "recordId"];</code>
   * @return The recordId.
   */
  com.google.protobuf.ByteString getRecordId();
}
