// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.recorder;

public final class RecorderProto {
  private RecorderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShiftStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShiftStartedRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftEndedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShiftEndedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShoeStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShoeStartedRequest_DecksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeEndedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShoeEndedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeEndedRequest_DecksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordShoeEndedRequest_DecksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_FortuneRatesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_FortuneRatesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundStepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundBeCanceledRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundBeCanceledRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundFinishedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundFinishedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_SetEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_AddEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_GetVideoUploadURLRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_GetVideoUploadURLRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_GetVideoUploadURLResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_GetVideoUploadURLResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_ListS3FoldersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_ListS3FoldersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_ListS3FoldersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_ListS3FoldersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_ListS3FilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_ListS3FilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_ListS3FilesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_ListS3FilesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_DeleteS3FileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_DeleteS3FileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_DeleteS3FileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_DeleteS3FileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordModifyCardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordModifyCardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordModifyCardRequest_ModifyFortuneEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordModifyCardRequest_ModifyFortuneEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_CardModify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_CardModify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordEventScreenshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recorder_RecordEventScreenshotRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027recorder/recorder.proto\022\010recorder\032\025rec" +
      "order/record.proto\032\037google/protobuf/time" +
      "stamp.proto\"/\n\020RecordIDResponse\022\033\n\trecor" +
      "d_id\030\001 \001(\014R\010recordId\"\250\003\n\031RecordShiftStar" +
      "tedRequest\022\032\n\010supplier\030\002 \001(\tR\010supplier\022\033" +
      "\n\tgame_type\030\003 \001(\tR\010gameType\022!\n\014game_subt" +
      "ype\030\004 \001(\tR\013gameSubtype\022!\n\014game_version\030\005" +
      " \001(\tR\013gameVersion\022\033\n\tgame_code\030\006 \001(\tR\010ga" +
      "meCode\022\035\n\ntable_code\030\007 \001(\tR\ttableCode\022\035\n" +
      "\nshift_code\030\010 \001(\tR\tshiftCode\0225\n\010ts_start" +
      "\030\020 \001(\0132\032.google.protobuf.TimestampR\007tsSt" +
      "art\022A\n\004tags\030\r \003(\0132-.recorder.RecordShift" +
      "StartedRequest.TagsEntryR\004tags\0327\n\tTagsEn" +
      "try\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005va" +
      "lue:\0028\001\"i\n\027RecordShiftEndedRequest\022\033\n\tre" +
      "cord_id\030\001 \001(\014R\010recordId\0221\n\006ts_end\030\023 \001(\0132" +
      "\032.google.protobuf.TimestampR\005tsEnd\"\364\003\n\030R" +
      "ecordShoeStartedRequest\022\032\n\010supplier\030\002 \001(" +
      "\tR\010supplier\022\033\n\tgame_type\030\003 \001(\tR\010gameType" +
      "\022!\n\014game_subtype\030\004 \001(\tR\013gameSubtype\022!\n\014g" +
      "ame_version\030\005 \001(\tR\013gameVersion\022\033\n\tgame_c" +
      "ode\030\006 \001(\tR\010gameCode\022\035\n\ntable_code\030\007 \001(\tR" +
      "\ttableCode\022\035\n\nshift_code\030\010 \001(\tR\tshiftCod" +
      "e\022\033\n\tshoe_code\030\n \001(\tR\010shoeCode\022\033\n\tcut_ro" +
      "und\030\013 \001(\005R\010cutRound\0225\n\010ts_start\030\020 \001(\0132\032." +
      "google.protobuf.TimestampR\007tsStart\022C\n\005de" +
      "cks\030\030 \003(\0132-.recorder.RecordShoeStartedRe" +
      "quest.DecksEntryR\005decks\032H\n\nDecksEntry\022\020\n" +
      "\003key\030\001 \001(\005R\003key\022$\n\005value\030\002 \001(\0132\016.recorde" +
      "r.DeckR\005value:\0028\001\"\365\001\n\026RecordShoeEndedReq" +
      "uest\022\033\n\trecord_id\030\001 \001(\014R\010recordId\0221\n\006ts_" +
      "end\030\023 \001(\0132\032.google.protobuf.TimestampR\005t" +
      "sEnd\022A\n\005decks\030\030 \003(\0132+.recorder.RecordSho" +
      "eEndedRequest.DecksEntryR\005decks\032H\n\nDecks" +
      "Entry\022\020\n\003key\030\001 \001(\005R\003key\022$\n\005value\030\002 \001(\0132\016" +
      ".recorder.DeckR\005value:\0028\001\"\342\007\n\031RecordRoun" +
      "dStartedRequest\022\032\n\010supplier\030\002 \001(\tR\010suppl" +
      "ier\022\033\n\tgame_type\030\003 \001(\tR\010gameType\022!\n\014game" +
      "_subtype\030\004 \001(\tR\013gameSubtype\022!\n\014game_vers" +
      "ion\030\005 \001(\tR\013gameVersion\022\033\n\tgame_code\030\006 \001(" +
      "\tR\010gameCode\022\035\n\ntable_code\030\007 \001(\tR\ttableCo" +
      "de\022\035\n\nshift_code\030\010 \001(\tR\tshiftCode\022\037\n\013shi" +
      "ft_round\030\t \001(\003R\nshiftRound\022\033\n\tshoe_code\030" +
      "\n \001(\tR\010shoeCode\022\035\n\nshoe_round\030\013 \001(\003R\tsho" +
      "eRound\022\035\n\nround_code\030\014 \001(\tR\troundCode\022A\n" +
      "\004tags\030\r \003(\0132-.recorder.RecordRoundStarte" +
      "dRequest.TagsEntryR\004tags\0225\n\010ts_start\030\020 \001" +
      "(\0132\032.google.protobuf.TimestampR\007tsStart\022" +
      "J\n\007players\030\031 \003(\01320.recorder.RecordRoundS" +
      "tartedRequest.PlayersEntryR\007players\022Z\n\rf" +
      "ortune_rates\030\035 \003(\01325.recorder.RecordRoun" +
      "dStartedRequest.FortuneRatesEntryR\014fortu" +
      "neRates\022W\n\014players_name\030\036 \003(\01324.recorder" +
      ".RecordRoundStartedRequest.PlayersNameEn" +
      "tryR\013playersName\0327\n\tTagsEntry\022\020\n\003key\030\001 \001" +
      "(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032:\n\014Pla" +
      "yersEntry\022\020\n\003key\030\001 \001(\005R\003key\022\024\n\005value\030\002 \001" +
      "(\tR\005value:\0028\001\032?\n\021FortuneRatesEntry\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\003R\005value:\0028\001\032>" +
      "\n\020PlayersNameEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005" +
      "value\030\002 \001(\tR\005value:\0028\001\"\\\n\027RecordRoundSte" +
      "psRequest\022\033\n\trecord_id\030\001 \001(\014R\010recordId\022$" +
      "\n\005steps\030\032 \003(\0132\016.recorder.StepR\005steps\"\266\001\n" +
      "\034RecordRoundBeCanceledRequest\022\033\n\trecord_" +
      "id\030\001 \001(\014R\010recordId\0221\n\006ts_end\030\023 \001(\0132\032.goo" +
      "gle.protobuf.TimestampR\005tsEnd\022\037\n\013cancel_" +
      "code\030\025 \001(\tR\ncancelCode\022%\n\016cancel_message" +
      "\030\026 \001(\tR\rcancelMessage\"l\n\032RecordRoundFini" +
      "shedRequest\022\033\n\trecord_id\030\001 \001(\014R\010recordId" +
      "\0221\n\006ts_end\030\023 \001(\0132\032.google.protobuf.Times" +
      "tampR\005tsEnd\"\272\002\n\027RecordRoundMediaRequest\022" +
      "\033\n\trecord_id\030\001 \001(\014R\010recordId\022<\n\003set\030\002 \003(" +
      "\0132*.recorder.RecordRoundMediaRequest.Set" +
      "EntryR\003set\022<\n\003add\030\003 \003(\0132*.recorder.Recor" +
      "dRoundMediaRequest.AddEntryR\003add\022\026\n\006remo" +
      "ve\030\004 \003(\tR\006remove\0326\n\010SetEntry\022\020\n\003key\030\001 \001(" +
      "\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\0326\n\010AddE" +
      "ntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005v" +
      "alue:\0028\001\"\213\001\n\030GetVideoUploadURLRequest\022\033\n" +
      "\trecord_id\030\001 \001(\014R\010recordId\022\035\n\nround_code" +
      "\030\002 \001(\tR\troundCode\022\026\n\006folder\030\003 \001(\tR\006folde" +
      "r\022\033\n\tgame_code\030\004 \001(\tR\010gameCode\"t\n\031GetVid" +
      "eoUploadURLResponse\022\035\n\nupload_url\030\001 \001(\tR" +
      "\tuploadUrl\022\033\n\tvideo_url\030\002 \001(\tR\010videoUrl\022" +
      "\033\n\trecord_id\030\003 \001(\014R\010recordId\"\026\n\024ListS3Fo" +
      "ldersRequest\"1\n\025ListS3FoldersResponse\022\030\n" +
      "\007folders\030\001 \003(\tR\007folders\"h\n\022ListS3FilesRe" +
      "quest\022\026\n\006folder\030\001 \001(\tR\006folder\022\033\n\tgame_co" +
      "de\030\002 \001(\tR\010gameCode\022\035\n\nround_code\030\003 \001(\tR\t" +
      "roundCode\")\n\023ListS3FilesResponse\022\022\n\004urls" +
      "\030\001 \003(\tR\004urls\"\'\n\023DeleteS3FileRequest\022\020\n\003k" +
      "ey\030\001 \001(\tR\003key\"\026\n\024DeleteS3FileResponse\"\315\002" +
      "\n\027RecordModifyCardRequest\022\033\n\tgame_code\030\002" +
      " \001(\tR\010gameCode\022\035\n\nround_code\030\003 \001(\tR\troun" +
      "dCode\0220\n\010modifies\030\004 \003(\0132\024.recorder.CardM" +
      "odifyR\010modifies\022%\n\016modify_message\030\005 \001(\tR" +
      "\rmodifyMessage\022[\n\016modify_fortune\030\006 \003(\01324" +
      ".recorder.RecordModifyCardRequest.Modify" +
      "FortuneEntryR\rmodifyFortune\032@\n\022ModifyFor" +
      "tuneEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001" +
      "(\003R\005value:\0028\001\"\212\001\n\nCardModify\022\022\n\004seat\030\001 \001" +
      "(\005R\004seat\022#\n\rresource_type\030\002 \001(\005R\014resourc" +
      "eType\022&\n\017card_list_index\030\003 \001(\003R\rcardList" +
      "Index\022\033\n\tcard_code\030\004 \001(\tR\010cardCode\"\210\001\n\034R" +
      "ecordEventScreenshotRequest\022\033\n\tgame_code" +
      "\030\002 \001(\tR\010gameCode\022\035\n\nevent_code\030\003 \001(\tR\tev" +
      "entCode\022\024\n\005cover\030\004 \001(\010R\005cover\022\026\n\006notify\030" +
      "\005 \001(\010R\006notify2\241\013\n\017RecorderService\022P\n\022Rec" +
      "ordShiftStarted\022#.recorder.RecordShiftSt" +
      "artedRequest\032\025.recorder.ShiftRecord\022L\n\020R" +
      "ecordShiftEnded\022!.recorder.RecordShiftEn" +
      "dedRequest\032\025.recorder.ShiftRecord\022M\n\021Rec" +
      "ordShoeStarted\022\".recorder.RecordShoeStar" +
      "tedRequest\032\024.recorder.ShoeRecord\022I\n\017Reco" +
      "rdShoeEnded\022 .recorder.RecordShoeEndedRe" +
      "quest\032\024.recorder.ShoeRecord\022P\n\022RecordRou" +
      "ndStarted\022#.recorder.RecordRoundStartedR" +
      "equest\032\025.recorder.RoundRecord\022L\n\020RecordR" +
      "oundSteps\022!.recorder.RecordRoundStepsReq" +
      "uest\032\025.recorder.RoundRecord\022V\n\025RecordRou" +
      "ndBeCanceled\022&.recorder.RecordRoundBeCan" +
      "celedRequest\032\025.recorder.RoundRecord\022R\n\023R" +
      "ecordRoundFinished\022$.recorder.RecordRoun" +
      "dFinishedRequest\032\025.recorder.RoundRecord\022" +
      "c\n\"RecordRoundBeCanceledAfterFinished\022&." +
      "recorder.RecordRoundBeCanceledRequest\032\025." +
      "recorder.RoundRecord\022X\n\034RecordModifyResu" +
      "ltAfterRound\022!.recorder.RecordModifyCard" +
      "Request\032\025.recorder.RoundRecord\022X\n\034Record" +
      "FinishResultAfterRound\022!.recorder.Record" +
      "ModifyCardRequest\032\025.recorder.RoundRecord" +
      "\022L\n\020RecordRoundVideo\022!.recorder.RecordRo" +
      "undMediaRequest\032\025.recorder.RoundRecord\022V" +
      "\n\025RecordEventScreenshot\022&.recorder.Recor" +
      "dEventScreenshotRequest\032\025.recorder.Round" +
      "Record\022\\\n\021GetVideoUploadURL\022\".recorder.G" +
      "etVideoUploadURLRequest\032#.recorder.GetVi" +
      "deoUploadURLResponse\022P\n\rListS3Folders\022\036." +
      "recorder.ListS3FoldersRequest\032\037.recorder" +
      ".ListS3FoldersResponse\022J\n\013ListS3Files\022\034." +
      "recorder.ListS3FilesRequest\032\035.recorder.L" +
      "istS3FilesResponse\022M\n\014DeleteS3File\022\035.rec" +
      "order.DeleteS3FileRequest\032\036.recorder.Del" +
      "eteS3FileResponseB\236\001\n\033com.wecasino.proto" +
      ".recorderB\rRecorderProtoP\001Z0github.com/w" +
      "ecasino/wecasino-proto/pbgo/recorder\242\002\003R" +
      "XX\252\002\010Recorder\312\002\010Recorder\342\002\024Recorder\\GPBM" +
      "etadata\352\002\010Recorderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wecasino.proto.recorder.RecordProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_recorder_RecordIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recorder_RecordIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordIDResponse_descriptor,
        new java.lang.String[] { "RecordId", });
    internal_static_recorder_RecordShiftStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recorder_RecordShiftStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShiftStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "TsStart", "Tags", });
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor =
      internal_static_recorder_RecordShiftStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordShiftEndedRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_recorder_RecordShiftEndedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShiftEndedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", });
    internal_static_recorder_RecordShoeStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_recorder_RecordShoeStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShoeStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "ShoeCode", "CutRound", "TsStart", "Decks", });
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor =
      internal_static_recorder_RecordShoeStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordShoeEndedRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_recorder_RecordShoeEndedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShoeEndedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", "Decks", });
    internal_static_recorder_RecordShoeEndedRequest_DecksEntry_descriptor =
      internal_static_recorder_RecordShoeEndedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordShoeEndedRequest_DecksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordShoeEndedRequest_DecksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "ShiftRound", "ShoeCode", "ShoeRound", "RoundCode", "Tags", "TsStart", "Players", "FortuneRates", "PlayersName", });
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor =
      internal_static_recorder_RecordRoundStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_descriptor =
      internal_static_recorder_RecordRoundStartedRequest_descriptor.getNestedTypes().get(1);
    internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStartedRequest_FortuneRatesEntry_descriptor =
      internal_static_recorder_RecordRoundStartedRequest_descriptor.getNestedTypes().get(2);
    internal_static_recorder_RecordRoundStartedRequest_FortuneRatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_FortuneRatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_descriptor =
      internal_static_recorder_RecordRoundStartedRequest_descriptor.getNestedTypes().get(3);
    internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_recorder_RecordRoundStepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundStepsRequest_descriptor,
        new java.lang.String[] { "RecordId", "Steps", });
    internal_static_recorder_RecordRoundBeCanceledRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_recorder_RecordRoundBeCanceledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundBeCanceledRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", "CancelCode", "CancelMessage", });
    internal_static_recorder_RecordRoundFinishedRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_recorder_RecordRoundFinishedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundFinishedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", });
    internal_static_recorder_RecordRoundMediaRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_descriptor,
        new java.lang.String[] { "RecordId", "Set", "Add", "Remove", });
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor =
      internal_static_recorder_RecordRoundMediaRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor =
      internal_static_recorder_RecordRoundMediaRequest_descriptor.getNestedTypes().get(1);
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_GetVideoUploadURLRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_recorder_GetVideoUploadURLRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_GetVideoUploadURLRequest_descriptor,
        new java.lang.String[] { "RecordId", "RoundCode", "Folder", "GameCode", });
    internal_static_recorder_GetVideoUploadURLResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_recorder_GetVideoUploadURLResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_GetVideoUploadURLResponse_descriptor,
        new java.lang.String[] { "UploadUrl", "VideoUrl", "RecordId", });
    internal_static_recorder_ListS3FoldersRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_recorder_ListS3FoldersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_ListS3FoldersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_recorder_ListS3FoldersResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_recorder_ListS3FoldersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_ListS3FoldersResponse_descriptor,
        new java.lang.String[] { "Folders", });
    internal_static_recorder_ListS3FilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_recorder_ListS3FilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_ListS3FilesRequest_descriptor,
        new java.lang.String[] { "Folder", "GameCode", "RoundCode", });
    internal_static_recorder_ListS3FilesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_recorder_ListS3FilesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_ListS3FilesResponse_descriptor,
        new java.lang.String[] { "Urls", });
    internal_static_recorder_DeleteS3FileRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_recorder_DeleteS3FileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_DeleteS3FileRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_recorder_DeleteS3FileResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_recorder_DeleteS3FileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_DeleteS3FileResponse_descriptor,
        new java.lang.String[] { });
    internal_static_recorder_RecordModifyCardRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_recorder_RecordModifyCardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordModifyCardRequest_descriptor,
        new java.lang.String[] { "GameCode", "RoundCode", "Modifies", "ModifyMessage", "ModifyFortune", });
    internal_static_recorder_RecordModifyCardRequest_ModifyFortuneEntry_descriptor =
      internal_static_recorder_RecordModifyCardRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordModifyCardRequest_ModifyFortuneEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordModifyCardRequest_ModifyFortuneEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_CardModify_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_recorder_CardModify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_CardModify_descriptor,
        new java.lang.String[] { "Seat", "ResourceType", "CardListIndex", "CardCode", });
    internal_static_recorder_RecordEventScreenshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_recorder_RecordEventScreenshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recorder_RecordEventScreenshotRequest_descriptor,
        new java.lang.String[] { "GameCode", "EventCode", "Cover", "Notify", });
    com.wecasino.proto.recorder.RecordProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
