// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto
// Protobuf Java Version: 4.26.1

package com.wecasino.proto.recorder;

public final class RecorderProto {
  private RecorderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RecorderProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShiftStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShiftStartedRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShiftEndedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShiftEndedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShoeStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShoeStartedRequest_DecksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordShoeEndedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordShoeEndedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundStartedRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundStepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundStepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundBeCanceledRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundBeCanceledRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundFinishedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundFinishedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_SetEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recorder_RecordRoundMediaRequest_AddEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027recorder/recorder.proto\022\010recorder\032\025rec" +
      "order/record.proto\032\037google/protobuf/time" +
      "stamp.proto\032\033google/protobuf/empty.proto" +
      "\"/\n\020RecordIDResponse\022\033\n\trecord_id\030\001 \001(\014R" +
      "\010recordId\"\250\003\n\031RecordShiftStartedRequest\022" +
      "\032\n\010supplier\030\002 \001(\tR\010supplier\022\033\n\tgame_type" +
      "\030\003 \001(\tR\010gameType\022!\n\014game_subtype\030\004 \001(\tR\013" +
      "gameSubtype\022!\n\014game_version\030\005 \001(\tR\013gameV" +
      "ersion\022\033\n\tgame_code\030\006 \001(\tR\010gameCode\022\035\n\nt" +
      "able_code\030\007 \001(\tR\ttableCode\022\035\n\nshift_code" +
      "\030\010 \001(\tR\tshiftCode\0225\n\010ts_start\030\020 \001(\0132\032.go" +
      "ogle.protobuf.TimestampR\007tsStart\022A\n\004tags" +
      "\030\r \003(\0132-.recorder.RecordShiftStartedRequ" +
      "est.TagsEntryR\004tags\0327\n\tTagsEntry\022\020\n\003key\030" +
      "\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"i\n\027" +
      "RecordShiftEndedRequest\022\033\n\trecord_id\030\001 \001" +
      "(\014R\010recordId\0221\n\006ts_end\030\023 \001(\0132\032.google.pr" +
      "otobuf.TimestampR\005tsEnd\"\327\003\n\030RecordShoeSt" +
      "artedRequest\022\032\n\010supplier\030\002 \001(\tR\010supplier" +
      "\022\033\n\tgame_type\030\003 \001(\tR\010gameType\022!\n\014game_su" +
      "btype\030\004 \001(\tR\013gameSubtype\022!\n\014game_version" +
      "\030\005 \001(\tR\013gameVersion\022\033\n\tgame_code\030\006 \001(\tR\010" +
      "gameCode\022\035\n\ntable_code\030\007 \001(\tR\ttableCode\022" +
      "\035\n\nshift_code\030\010 \001(\tR\tshiftCode\022\033\n\tshoe_c" +
      "ode\030\n \001(\tR\010shoeCode\0225\n\010ts_start\030\020 \001(\0132\032." +
      "google.protobuf.TimestampR\007tsStart\022C\n\005de" +
      "cks\030\030 \003(\0132-.recorder.RecordShoeStartedRe" +
      "quest.DecksEntryR\005decks\032H\n\nDecksEntry\022\020\n" +
      "\003key\030\001 \001(\005R\003key\022$\n\005value\030\002 \001(\0132\016.recorde" +
      "r.DeckR\005value:\0028\001\"h\n\026RecordShoeEndedRequ" +
      "est\022\033\n\trecord_id\030\001 \001(\014R\010recordId\0221\n\006ts_e" +
      "nd\030\023 \001(\0132\032.google.protobuf.TimestampR\005ts" +
      "End\"\244\004\n\031RecordRoundStartedRequest\022\032\n\010sup" +
      "plier\030\002 \001(\tR\010supplier\022\033\n\tgame_type\030\003 \001(\t" +
      "R\010gameType\022!\n\014game_subtype\030\004 \001(\tR\013gameSu" +
      "btype\022!\n\014game_version\030\005 \001(\tR\013gameVersion" +
      "\022\033\n\tgame_code\030\006 \001(\tR\010gameCode\022\035\n\ntable_c" +
      "ode\030\007 \001(\tR\ttableCode\022\035\n\nshift_code\030\010 \001(\t" +
      "R\tshiftCode\022\037\n\013shift_round\030\t \001(\003R\nshiftR" +
      "ound\022\033\n\tshoe_code\030\n \001(\tR\010shoeCode\022\035\n\nsho" +
      "e_round\030\013 \001(\003R\tshoeRound\022\035\n\nround_code\030\014" +
      " \001(\tR\troundCode\022A\n\004tags\030\r \003(\0132-.recorder" +
      ".RecordRoundStartedRequest.TagsEntryR\004ta" +
      "gs\0225\n\010ts_start\030\020 \001(\0132\032.google.protobuf.T" +
      "imestampR\007tsStart\0327\n\tTagsEntry\022\020\n\003key\030\001 " +
      "\001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"\\\n\027Re" +
      "cordRoundStepsRequest\022\033\n\trecord_id\030\001 \001(\014" +
      "R\010recordId\022$\n\005steps\030\032 \003(\0132\016.recorder.Ste" +
      "pR\005steps\"\266\001\n\034RecordRoundBeCanceledReques" +
      "t\022\033\n\trecord_id\030\001 \001(\014R\010recordId\0221\n\006ts_end" +
      "\030\023 \001(\0132\032.google.protobuf.TimestampR\005tsEn" +
      "d\022\037\n\013cancel_code\030\025 \001(\tR\ncancelCode\022%\n\016ca" +
      "ncel_message\030\026 \001(\tR\rcancelMessage\"l\n\032Rec" +
      "ordRoundFinishedRequest\022\033\n\trecord_id\030\001 \001" +
      "(\014R\010recordId\0221\n\006ts_end\030\023 \001(\0132\032.google.pr" +
      "otobuf.TimestampR\005tsEnd\"\272\002\n\027RecordRoundM" +
      "ediaRequest\022\033\n\trecord_id\030\001 \001(\014R\010recordId" +
      "\022<\n\003set\030\002 \003(\0132*.recorder.RecordRoundMedi" +
      "aRequest.SetEntryR\003set\022<\n\003add\030\003 \003(\0132*.re" +
      "corder.RecordRoundMediaRequest.AddEntryR" +
      "\003add\022\026\n\006remove\030\004 \003(\tR\006remove\0326\n\010SetEntry" +
      "\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value" +
      ":\0028\001\0326\n\010AddEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005va" +
      "lue\030\002 \001(\tR\005value:\0028\0012\270\006\n\017RecorderService" +
      "\022P\n\022RecordShiftStarted\022#.recorder.Record" +
      "ShiftStartedRequest\032\025.recorder.ShiftReco" +
      "rd\022L\n\020RecordShiftEnded\022!.recorder.Record" +
      "ShiftEndedRequest\032\025.recorder.ShiftRecord" +
      "\022M\n\021RecordShoeStarted\022\".recorder.RecordS" +
      "hoeStartedRequest\032\024.recorder.ShoeRecord\022" +
      "I\n\017RecordShoeEnded\022 .recorder.RecordShoe" +
      "EndedRequest\032\024.recorder.ShoeRecord\022P\n\022Re" +
      "cordRoundStarted\022#.recorder.RecordRoundS" +
      "tartedRequest\032\025.recorder.RoundRecord\022L\n\020" +
      "RecordRoundSteps\022!.recorder.RecordRoundS" +
      "tepsRequest\032\025.recorder.RoundRecord\022V\n\025Re" +
      "cordRoundBeCanceled\022&.recorder.RecordRou" +
      "ndBeCanceledRequest\032\025.recorder.RoundReco" +
      "rd\022R\n\023RecordRoundFinished\022$.recorder.Rec" +
      "ordRoundFinishedRequest\032\025.recorder.Round" +
      "Record\022L\n\020RecordRoundVideo\022!.recorder.Re" +
      "cordRoundMediaRequest\032\025.recorder.RoundRe" +
      "cord\022Q\n\022RecordCaptureFrame\022#.recorder.Re" +
      "cordRoundStartedRequest\032\026.google.protobu" +
      "f.EmptyB\236\001\n\033com.wecasino.proto.recorderB" +
      "\rRecorderProtoP\001Z0github.com/wecasino/we" +
      "casino-proto/pbgo/recorder\242\002\003RXX\252\002\010Recor" +
      "der\312\002\010Recorder\342\002\024Recorder\\GPBMetadata\352\002\010" +
      "Recorderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wecasino.proto.recorder.RecordProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_recorder_RecordIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recorder_RecordIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordIDResponse_descriptor,
        new java.lang.String[] { "RecordId", });
    internal_static_recorder_RecordShiftStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recorder_RecordShiftStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShiftStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "TsStart", "Tags", });
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor =
      internal_static_recorder_RecordShiftStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordShiftStartedRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShiftStartedRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordShiftEndedRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_recorder_RecordShiftEndedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShiftEndedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", });
    internal_static_recorder_RecordShoeStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_recorder_RecordShoeStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShoeStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "ShoeCode", "TsStart", "Decks", });
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor =
      internal_static_recorder_RecordShoeStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordShoeStartedRequest_DecksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShoeStartedRequest_DecksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordShoeEndedRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_recorder_RecordShoeEndedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordShoeEndedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", });
    internal_static_recorder_RecordRoundStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_descriptor,
        new java.lang.String[] { "Supplier", "GameType", "GameSubtype", "GameVersion", "GameCode", "TableCode", "ShiftCode", "ShiftRound", "ShoeCode", "ShoeRound", "RoundCode", "Tags", "TsStart", });
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor =
      internal_static_recorder_RecordRoundStartedRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordRoundStartedRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundStepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_recorder_RecordRoundStepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundStepsRequest_descriptor,
        new java.lang.String[] { "RecordId", "Steps", });
    internal_static_recorder_RecordRoundBeCanceledRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_recorder_RecordRoundBeCanceledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundBeCanceledRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", "CancelCode", "CancelMessage", });
    internal_static_recorder_RecordRoundFinishedRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_recorder_RecordRoundFinishedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundFinishedRequest_descriptor,
        new java.lang.String[] { "RecordId", "TsEnd", });
    internal_static_recorder_RecordRoundMediaRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_descriptor,
        new java.lang.String[] { "RecordId", "Set", "Add", "Remove", });
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor =
      internal_static_recorder_RecordRoundMediaRequest_descriptor.getNestedTypes().get(0);
    internal_static_recorder_RecordRoundMediaRequest_SetEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor =
      internal_static_recorder_RecordRoundMediaRequest_descriptor.getNestedTypes().get(1);
    internal_static_recorder_RecordRoundMediaRequest_AddEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.wecasino.proto.recorder.RecordProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
