// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

/**
 * <pre>
 * 紀錄回放
 * </pre>
 *
 * Protobuf type {@code recorder.RecordRoundMediaRequest}
 */
public final class RecordRoundMediaRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder.RecordRoundMediaRequest)
    RecordRoundMediaRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RecordRoundMediaRequest.class.getName());
  }
  // Use RecordRoundMediaRequest.newBuilder() to construct.
  private RecordRoundMediaRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecordRoundMediaRequest() {
    recordId_ = com.google.protobuf.ByteString.EMPTY;
    remove_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetSet();
      case 3:
        return internalGetAdd();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wecasino.proto.recorder.RecordRoundMediaRequest.class, com.wecasino.proto.recorder.RecordRoundMediaRequest.Builder.class);
  }

  public static final int RECORD_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString recordId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 遊戲局紀錄ID
   * </pre>
   *
   * <code>bytes record_id = 1 [json_name = "recordId"];</code>
   * @return The recordId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRecordId() {
    return recordId_;
  }

  public static final int SET_FIELD_NUMBER = 2;
  private static final class SetDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_SetEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> set_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetSet() {
    if (set_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SetDefaultEntryHolder.defaultEntry);
    }
    return set_;
  }
  public int getSetCount() {
    return internalGetSet().getMap().size();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
   */
  @java.lang.Override
  public boolean containsSet(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSet().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSetMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getSet() {
    return getSetMap();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getSetMap() {
    return internalGetSet().getMap();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getSetOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSet().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
   */
  @java.lang.Override
  public java.lang.String getSetOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSet().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ADD_FIELD_NUMBER = 3;
  private static final class AddDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_AddEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> add_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAdd() {
    if (add_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AddDefaultEntryHolder.defaultEntry);
    }
    return add_;
  }
  public int getAddCount() {
    return internalGetAdd().getMap().size();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
   */
  @java.lang.Override
  public boolean containsAdd(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAdd().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAddMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAdd() {
    return getAddMap();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getAddMap() {
    return internalGetAdd().getMap();
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getAddOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAdd().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
   * </pre>
   *
   * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
   */
  @java.lang.Override
  public java.lang.String getAddOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAdd().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int REMOVE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList remove_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 移除
   * </pre>
   *
   * <code>repeated string remove = 4 [json_name = "remove"];</code>
   * @return A list containing the remove.
   */
  public com.google.protobuf.ProtocolStringList
      getRemoveList() {
    return remove_;
  }
  /**
   * <pre>
   * 移除
   * </pre>
   *
   * <code>repeated string remove = 4 [json_name = "remove"];</code>
   * @return The count of remove.
   */
  public int getRemoveCount() {
    return remove_.size();
  }
  /**
   * <pre>
   * 移除
   * </pre>
   *
   * <code>repeated string remove = 4 [json_name = "remove"];</code>
   * @param index The index of the element to return.
   * @return The remove at the given index.
   */
  public java.lang.String getRemove(int index) {
    return remove_.get(index);
  }
  /**
   * <pre>
   * 移除
   * </pre>
   *
   * <code>repeated string remove = 4 [json_name = "remove"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the remove at the given index.
   */
  public com.google.protobuf.ByteString
      getRemoveBytes(int index) {
    return remove_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!recordId_.isEmpty()) {
      output.writeBytes(1, recordId_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetSet(),
        SetDefaultEntryHolder.defaultEntry,
        2);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetAdd(),
        AddDefaultEntryHolder.defaultEntry,
        3);
    for (int i = 0; i < remove_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, remove_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!recordId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, recordId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetSet().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      set__ = SetDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, set__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAdd().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      add__ = AddDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, add__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < remove_.size(); i++) {
        dataSize += computeStringSizeNoTag(remove_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRemoveList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wecasino.proto.recorder.RecordRoundMediaRequest)) {
      return super.equals(obj);
    }
    com.wecasino.proto.recorder.RecordRoundMediaRequest other = (com.wecasino.proto.recorder.RecordRoundMediaRequest) obj;

    if (!getRecordId()
        .equals(other.getRecordId())) return false;
    if (!internalGetSet().equals(
        other.internalGetSet())) return false;
    if (!internalGetAdd().equals(
        other.internalGetAdd())) return false;
    if (!getRemoveList()
        .equals(other.getRemoveList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRecordId().hashCode();
    if (!internalGetSet().getMap().isEmpty()) {
      hash = (37 * hash) + SET_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSet().hashCode();
    }
    if (!internalGetAdd().getMap().isEmpty()) {
      hash = (37 * hash) + ADD_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAdd().hashCode();
    }
    if (getRemoveCount() > 0) {
      hash = (37 * hash) + REMOVE_FIELD_NUMBER;
      hash = (53 * hash) + getRemoveList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.RecordRoundMediaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wecasino.proto.recorder.RecordRoundMediaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 紀錄回放
   * </pre>
   *
   * Protobuf type {@code recorder.RecordRoundMediaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder.RecordRoundMediaRequest)
      com.wecasino.proto.recorder.RecordRoundMediaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetSet();
        case 3:
          return internalGetAdd();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableSet();
        case 3:
          return internalGetMutableAdd();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wecasino.proto.recorder.RecordRoundMediaRequest.class, com.wecasino.proto.recorder.RecordRoundMediaRequest.Builder.class);
    }

    // Construct using com.wecasino.proto.recorder.RecordRoundMediaRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recordId_ = com.google.protobuf.ByteString.EMPTY;
      internalGetMutableSet().clear();
      internalGetMutableAdd().clear();
      remove_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundMediaRequest_descriptor;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundMediaRequest getDefaultInstanceForType() {
      return com.wecasino.proto.recorder.RecordRoundMediaRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundMediaRequest build() {
      com.wecasino.proto.recorder.RecordRoundMediaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundMediaRequest buildPartial() {
      com.wecasino.proto.recorder.RecordRoundMediaRequest result = new com.wecasino.proto.recorder.RecordRoundMediaRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.wecasino.proto.recorder.RecordRoundMediaRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recordId_ = recordId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.set_ = internalGetSet();
        result.set_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.add_ = internalGetAdd();
        result.add_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        remove_.makeImmutable();
        result.remove_ = remove_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wecasino.proto.recorder.RecordRoundMediaRequest) {
        return mergeFrom((com.wecasino.proto.recorder.RecordRoundMediaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wecasino.proto.recorder.RecordRoundMediaRequest other) {
      if (other == com.wecasino.proto.recorder.RecordRoundMediaRequest.getDefaultInstance()) return this;
      if (other.getRecordId() != com.google.protobuf.ByteString.EMPTY) {
        setRecordId(other.getRecordId());
      }
      internalGetMutableSet().mergeFrom(
          other.internalGetSet());
      bitField0_ |= 0x00000002;
      internalGetMutableAdd().mergeFrom(
          other.internalGetAdd());
      bitField0_ |= 0x00000004;
      if (!other.remove_.isEmpty()) {
        if (remove_.isEmpty()) {
          remove_ = other.remove_;
          bitField0_ |= 0x00000008;
        } else {
          ensureRemoveIsMutable();
          remove_.addAll(other.remove_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              recordId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              set__ = input.readMessage(
                  SetDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSet().getMutableMap().put(
                  set__.getKey(), set__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              add__ = input.readMessage(
                  AddDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAdd().getMutableMap().put(
                  add__.getKey(), add__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRemoveIsMutable();
              remove_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString recordId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 遊戲局紀錄ID
     * </pre>
     *
     * <code>bytes record_id = 1 [json_name = "recordId"];</code>
     * @return The recordId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRecordId() {
      return recordId_;
    }
    /**
     * <pre>
     * 遊戲局紀錄ID
     * </pre>
     *
     * <code>bytes record_id = 1 [json_name = "recordId"];</code>
     * @param value The recordId to set.
     * @return This builder for chaining.
     */
    public Builder setRecordId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      recordId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲局紀錄ID
     * </pre>
     *
     * <code>bytes record_id = 1 [json_name = "recordId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      recordId_ = getDefaultInstance().getRecordId();
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> set_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSet() {
      if (set_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetDefaultEntryHolder.defaultEntry);
      }
      return set_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableSet() {
      if (set_ == null) {
        set_ = com.google.protobuf.MapField.newMapField(
            SetDefaultEntryHolder.defaultEntry);
      }
      if (!set_.isMutable()) {
        set_ = set_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return set_;
    }
    public int getSetCount() {
      return internalGetSet().getMap().size();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    @java.lang.Override
    public boolean containsSet(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSet().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSetMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSet() {
      return getSetMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getSetMap() {
      return internalGetSet().getMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getSetOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSet().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    @java.lang.Override
    public java.lang.String getSetOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSet().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearSet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableSet().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    public Builder removeSet(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSet().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableSet() {
      bitField0_ |= 0x00000002;
      return internalGetMutableSet().getMutableMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    public Builder putSet(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableSet().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; set = 2 [json_name = "set"];</code>
     */
    public Builder putAllSet(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableSet().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> add_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAdd() {
      if (add_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AddDefaultEntryHolder.defaultEntry);
      }
      return add_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableAdd() {
      if (add_ == null) {
        add_ = com.google.protobuf.MapField.newMapField(
            AddDefaultEntryHolder.defaultEntry);
      }
      if (!add_.isMutable()) {
        add_ = add_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return add_;
    }
    public int getAddCount() {
      return internalGetAdd().getMap().size();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    @java.lang.Override
    public boolean containsAdd(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAdd().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAddMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAdd() {
      return getAddMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAddMap() {
      return internalGetAdd().getMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getAddOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdd().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    @java.lang.Override
    public java.lang.String getAddOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdd().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearAdd() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableAdd().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    public Builder removeAdd(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAdd().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableAdd() {
      bitField0_ |= 0x00000004;
      return internalGetMutableAdd().getMutableMap();
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    public Builder putAdd(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableAdd().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * 附加媒體：key: 媒體資源代碼；value: 媒體內容。
     * </pre>
     *
     * <code>map&lt;string, string&gt; add = 3 [json_name = "add"];</code>
     */
    public Builder putAllAdd(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAdd().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private com.google.protobuf.LazyStringArrayList remove_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRemoveIsMutable() {
      if (!remove_.isModifiable()) {
        remove_ = new com.google.protobuf.LazyStringArrayList(remove_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @return A list containing the remove.
     */
    public com.google.protobuf.ProtocolStringList
        getRemoveList() {
      remove_.makeImmutable();
      return remove_;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @return The count of remove.
     */
    public int getRemoveCount() {
      return remove_.size();
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param index The index of the element to return.
     * @return The remove at the given index.
     */
    public java.lang.String getRemove(int index) {
      return remove_.get(index);
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the remove at the given index.
     */
    public com.google.protobuf.ByteString
        getRemoveBytes(int index) {
      return remove_.getByteString(index);
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param index The index to set the value at.
     * @param value The remove to set.
     * @return This builder for chaining.
     */
    public Builder setRemove(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRemoveIsMutable();
      remove_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param value The remove to add.
     * @return This builder for chaining.
     */
    public Builder addRemove(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRemoveIsMutable();
      remove_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param values The remove to add.
     * @return This builder for chaining.
     */
    public Builder addAllRemove(
        java.lang.Iterable<java.lang.String> values) {
      ensureRemoveIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, remove_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRemove() {
      remove_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 移除
     * </pre>
     *
     * <code>repeated string remove = 4 [json_name = "remove"];</code>
     * @param value The bytes of the remove to add.
     * @return This builder for chaining.
     */
    public Builder addRemoveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRemoveIsMutable();
      remove_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:recorder.RecordRoundMediaRequest)
  }

  // @@protoc_insertion_point(class_scope:recorder.RecordRoundMediaRequest)
  private static final com.wecasino.proto.recorder.RecordRoundMediaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wecasino.proto.recorder.RecordRoundMediaRequest();
  }

  public static com.wecasino.proto.recorder.RecordRoundMediaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordRoundMediaRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecordRoundMediaRequest>() {
    @java.lang.Override
    public RecordRoundMediaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordRoundMediaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordRoundMediaRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wecasino.proto.recorder.RecordRoundMediaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

