// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

/**
 * Protobuf type {@code recorder.RecordRoundStartedRequest}
 */
public final class RecordRoundStartedRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder.RecordRoundStartedRequest)
    RecordRoundStartedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RecordRoundStartedRequest.class.getName());
  }
  // Use RecordRoundStartedRequest.newBuilder() to construct.
  private RecordRoundStartedRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecordRoundStartedRequest() {
    supplier_ = "";
    gameType_ = "";
    gameSubtype_ = "";
    gameVersion_ = "";
    gameCode_ = "";
    tableCode_ = "";
    shiftCode_ = "";
    shoeCode_ = "";
    roundCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 13:
        return internalGetTags();
      case 25:
        return internalGetPlayers();
      case 30:
        return internalGetPlayersName();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wecasino.proto.recorder.RecordRoundStartedRequest.class, com.wecasino.proto.recorder.RecordRoundStartedRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SUPPLIER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object supplier_ = "";
  /**
   * <pre>
   * 遊戲供應
   * </pre>
   *
   * <code>string supplier = 2 [json_name = "supplier"];</code>
   * @return The supplier.
   */
  @java.lang.Override
  public java.lang.String getSupplier() {
    java.lang.Object ref = supplier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      supplier_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 遊戲供應
   * </pre>
   *
   * <code>string supplier = 2 [json_name = "supplier"];</code>
   * @return The bytes for supplier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSupplierBytes() {
    java.lang.Object ref = supplier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      supplier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameType_ = "";
  /**
   * <pre>
   * 遊戲類型
   * </pre>
   *
   * <code>string game_type = 3 [json_name = "gameType"];</code>
   * @return The gameType.
   */
  @java.lang.Override
  public java.lang.String getGameType() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 遊戲類型
   * </pre>
   *
   * <code>string game_type = 3 [json_name = "gameType"];</code>
   * @return The bytes for gameType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameTypeBytes() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_SUBTYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameSubtype_ = "";
  /**
   * <pre>
   * 遊戲子類型
   * </pre>
   *
   * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
   * @return The gameSubtype.
   */
  @java.lang.Override
  public java.lang.String getGameSubtype() {
    java.lang.Object ref = gameSubtype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameSubtype_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 遊戲子類型
   * </pre>
   *
   * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
   * @return The bytes for gameSubtype.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameSubtypeBytes() {
    java.lang.Object ref = gameSubtype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameSubtype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_VERSION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameVersion_ = "";
  /**
   * <pre>
   * 遊戲版本
   * </pre>
   *
   * <code>string game_version = 5 [json_name = "gameVersion"];</code>
   * @return The gameVersion.
   */
  @java.lang.Override
  public java.lang.String getGameVersion() {
    java.lang.Object ref = gameVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 遊戲版本
   * </pre>
   *
   * <code>string game_version = 5 [json_name = "gameVersion"];</code>
   * @return The bytes for gameVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameVersionBytes() {
    java.lang.Object ref = gameVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_CODE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameCode_ = "";
  /**
   * <pre>
   * 遊戲代碼
   * </pre>
   *
   * <code>string game_code = 6 [json_name = "gameCode"];</code>
   * @return The gameCode.
   */
  @java.lang.Override
  public java.lang.String getGameCode() {
    java.lang.Object ref = gameCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 遊戲代碼
   * </pre>
   *
   * <code>string game_code = 6 [json_name = "gameCode"];</code>
   * @return The bytes for gameCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameCodeBytes() {
    java.lang.Object ref = gameCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLE_CODE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableCode_ = "";
  /**
   * <pre>
   * 桌代碼
   * </pre>
   *
   * <code>string table_code = 7 [json_name = "tableCode"];</code>
   * @return The tableCode.
   */
  @java.lang.Override
  public java.lang.String getTableCode() {
    java.lang.Object ref = tableCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 桌代碼
   * </pre>
   *
   * <code>string table_code = 7 [json_name = "tableCode"];</code>
   * @return The bytes for tableCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableCodeBytes() {
    java.lang.Object ref = tableCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIFT_CODE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object shiftCode_ = "";
  /**
   * <pre>
   * 班代碼
   * </pre>
   *
   * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
   * @return The shiftCode.
   */
  @java.lang.Override
  public java.lang.String getShiftCode() {
    java.lang.Object ref = shiftCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shiftCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 班代碼
   * </pre>
   *
   * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
   * @return The bytes for shiftCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShiftCodeBytes() {
    java.lang.Object ref = shiftCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shiftCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIFT_ROUND_FIELD_NUMBER = 9;
  private long shiftRound_ = 0L;
  /**
   * <pre>
   * 此排班局數
   * </pre>
   *
   * <code>int64 shift_round = 9 [json_name = "shiftRound"];</code>
   * @return The shiftRound.
   */
  @java.lang.Override
  public long getShiftRound() {
    return shiftRound_;
  }

  public static final int SHOE_CODE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object shoeCode_ = "";
  /**
   * <pre>
   * 使用洗牌代碼
   * </pre>
   *
   * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
   * @return The shoeCode.
   */
  @java.lang.Override
  public java.lang.String getShoeCode() {
    java.lang.Object ref = shoeCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shoeCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 使用洗牌代碼
   * </pre>
   *
   * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
   * @return The bytes for shoeCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShoeCodeBytes() {
    java.lang.Object ref = shoeCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shoeCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOE_ROUND_FIELD_NUMBER = 11;
  private long shoeRound_ = 0L;
  /**
   * <pre>
   * 使用此洗牌第幾局，從1開始計算
   * </pre>
   *
   * <code>int64 shoe_round = 11 [json_name = "shoeRound"];</code>
   * @return The shoeRound.
   */
  @java.lang.Override
  public long getShoeRound() {
    return shoeRound_;
  }

  public static final int ROUND_CODE_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roundCode_ = "";
  /**
   * <pre>
   * 局代碼
   * </pre>
   *
   * <code>string round_code = 12 [json_name = "roundCode"];</code>
   * @return The roundCode.
   */
  @java.lang.Override
  public java.lang.String getRoundCode() {
    java.lang.Object ref = roundCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roundCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 局代碼
   * </pre>
   *
   * <code>string round_code = 12 [json_name = "roundCode"];</code>
   * @return The bytes for roundCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoundCodeBytes() {
    java.lang.Object ref = roundCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roundCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 13;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_TagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }
  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <pre>
   * 標籤
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
   */
  @java.lang.Override
  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <pre>
   * 標籤
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <pre>
   * 標籤
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 標籤
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
   */
  @java.lang.Override
  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TS_START_FIELD_NUMBER = 16;
  private com.google.protobuf.Timestamp tsStart_;
  /**
   * <pre>
   * 開始時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   * @return Whether the tsStart field is set.
   */
  @java.lang.Override
  public boolean hasTsStart() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 開始時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   * @return The tsStart.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTsStart() {
    return tsStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : tsStart_;
  }
  /**
   * <pre>
   * 開始時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTsStartOrBuilder() {
    return tsStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : tsStart_;
  }

  public static final int PLAYERS_FIELD_NUMBER = 25;
  private static final class PlayersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.String>newDefaultInstance(
                com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_PlayersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.String> players_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
  internalGetPlayers() {
    if (players_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PlayersDefaultEntryHolder.defaultEntry);
    }
    return players_;
  }
  public int getPlayersCount() {
    return internalGetPlayers().getMap().size();
  }
  /**
   * <pre>
   * 玩家入座
   * </pre>
   *
   * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
   */
  @java.lang.Override
  public boolean containsPlayers(
      int key) {

    return internalGetPlayers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPlayersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.String> getPlayers() {
    return getPlayersMap();
  }
  /**
   * <pre>
   * 玩家入座
   * </pre>
   *
   * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, java.lang.String> getPlayersMap() {
    return internalGetPlayers().getMap();
  }
  /**
   * <pre>
   * 玩家入座
   * </pre>
   *
   * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getPlayersOrDefault(
      int key,
      /* nullable */
java.lang.String defaultValue) {

    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetPlayers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 玩家入座
   * </pre>
   *
   * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
   */
  @java.lang.Override
  public java.lang.String getPlayersOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetPlayers().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PLAYERS_NAME_FIELD_NUMBER = 30;
  private static final class PlayersNameDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_PlayersNameEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> playersName_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetPlayersName() {
    if (playersName_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PlayersNameDefaultEntryHolder.defaultEntry);
    }
    return playersName_;
  }
  public int getPlayersNameCount() {
    return internalGetPlayersName().getMap().size();
  }
  /**
   * <pre>
   * 玩家姓名
   * </pre>
   *
   * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
   */
  @java.lang.Override
  public boolean containsPlayersName(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPlayersName().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPlayersNameMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getPlayersName() {
    return getPlayersNameMap();
  }
  /**
   * <pre>
   * 玩家姓名
   * </pre>
   *
   * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getPlayersNameMap() {
    return internalGetPlayersName().getMap();
  }
  /**
   * <pre>
   * 玩家姓名
   * </pre>
   *
   * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getPlayersNameOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetPlayersName().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 玩家姓名
   * </pre>
   *
   * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
   */
  @java.lang.Override
  public java.lang.String getPlayersNameOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetPlayersName().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(supplier_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, supplier_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, gameType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameSubtype_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, gameSubtype_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, gameVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, gameCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tableCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, tableCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shiftCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, shiftCode_);
    }
    if (shiftRound_ != 0L) {
      output.writeInt64(9, shiftRound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shoeCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, shoeCode_);
    }
    if (shoeRound_ != 0L) {
      output.writeInt64(11, shoeRound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roundCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, roundCode_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        13);
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(16, getTsStart());
    }
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetPlayers(),
        PlayersDefaultEntryHolder.defaultEntry,
        25);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetPlayersName(),
        PlayersNameDefaultEntryHolder.defaultEntry,
        30);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(supplier_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, supplier_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, gameType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameSubtype_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, gameSubtype_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, gameVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, gameCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tableCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, tableCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shiftCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, shiftCode_);
    }
    if (shiftRound_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, shiftRound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shoeCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, shoeCode_);
    }
    if (shoeRound_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, shoeRound_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roundCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, roundCode_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, tags__);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getTsStart());
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
         : internalGetPlayers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
      players__ = PlayersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(25, players__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetPlayersName().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      playersName__ = PlayersNameDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(30, playersName__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wecasino.proto.recorder.RecordRoundStartedRequest)) {
      return super.equals(obj);
    }
    com.wecasino.proto.recorder.RecordRoundStartedRequest other = (com.wecasino.proto.recorder.RecordRoundStartedRequest) obj;

    if (!getSupplier()
        .equals(other.getSupplier())) return false;
    if (!getGameType()
        .equals(other.getGameType())) return false;
    if (!getGameSubtype()
        .equals(other.getGameSubtype())) return false;
    if (!getGameVersion()
        .equals(other.getGameVersion())) return false;
    if (!getGameCode()
        .equals(other.getGameCode())) return false;
    if (!getTableCode()
        .equals(other.getTableCode())) return false;
    if (!getShiftCode()
        .equals(other.getShiftCode())) return false;
    if (getShiftRound()
        != other.getShiftRound()) return false;
    if (!getShoeCode()
        .equals(other.getShoeCode())) return false;
    if (getShoeRound()
        != other.getShoeRound()) return false;
    if (!getRoundCode()
        .equals(other.getRoundCode())) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (hasTsStart() != other.hasTsStart()) return false;
    if (hasTsStart()) {
      if (!getTsStart()
          .equals(other.getTsStart())) return false;
    }
    if (!internalGetPlayers().equals(
        other.internalGetPlayers())) return false;
    if (!internalGetPlayersName().equals(
        other.internalGetPlayersName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUPPLIER_FIELD_NUMBER;
    hash = (53 * hash) + getSupplier().hashCode();
    hash = (37 * hash) + GAME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGameType().hashCode();
    hash = (37 * hash) + GAME_SUBTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGameSubtype().hashCode();
    hash = (37 * hash) + GAME_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getGameVersion().hashCode();
    hash = (37 * hash) + GAME_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getGameCode().hashCode();
    hash = (37 * hash) + TABLE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getTableCode().hashCode();
    hash = (37 * hash) + SHIFT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getShiftCode().hashCode();
    hash = (37 * hash) + SHIFT_ROUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getShiftRound());
    hash = (37 * hash) + SHOE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getShoeCode().hashCode();
    hash = (37 * hash) + SHOE_ROUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getShoeRound());
    hash = (37 * hash) + ROUND_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoundCode().hashCode();
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    if (hasTsStart()) {
      hash = (37 * hash) + TS_START_FIELD_NUMBER;
      hash = (53 * hash) + getTsStart().hashCode();
    }
    if (!internalGetPlayers().getMap().isEmpty()) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPlayers().hashCode();
    }
    if (!internalGetPlayersName().getMap().isEmpty()) {
      hash = (37 * hash) + PLAYERS_NAME_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPlayersName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.wecasino.proto.recorder.RecordRoundStartedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wecasino.proto.recorder.RecordRoundStartedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder.RecordRoundStartedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder.RecordRoundStartedRequest)
      com.wecasino.proto.recorder.RecordRoundStartedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 13:
          return internalGetTags();
        case 25:
          return internalGetPlayers();
        case 30:
          return internalGetPlayersName();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 13:
          return internalGetMutableTags();
        case 25:
          return internalGetMutablePlayers();
        case 30:
          return internalGetMutablePlayersName();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wecasino.proto.recorder.RecordRoundStartedRequest.class, com.wecasino.proto.recorder.RecordRoundStartedRequest.Builder.class);
    }

    // Construct using com.wecasino.proto.recorder.RecordRoundStartedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTsStartFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      supplier_ = "";
      gameType_ = "";
      gameSubtype_ = "";
      gameVersion_ = "";
      gameCode_ = "";
      tableCode_ = "";
      shiftCode_ = "";
      shiftRound_ = 0L;
      shoeCode_ = "";
      shoeRound_ = 0L;
      roundCode_ = "";
      internalGetMutableTags().clear();
      tsStart_ = null;
      if (tsStartBuilder_ != null) {
        tsStartBuilder_.dispose();
        tsStartBuilder_ = null;
      }
      internalGetMutablePlayers().clear();
      internalGetMutablePlayersName().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wecasino.proto.recorder.RecorderProto.internal_static_recorder_RecordRoundStartedRequest_descriptor;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundStartedRequest getDefaultInstanceForType() {
      return com.wecasino.proto.recorder.RecordRoundStartedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundStartedRequest build() {
      com.wecasino.proto.recorder.RecordRoundStartedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wecasino.proto.recorder.RecordRoundStartedRequest buildPartial() {
      com.wecasino.proto.recorder.RecordRoundStartedRequest result = new com.wecasino.proto.recorder.RecordRoundStartedRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.wecasino.proto.recorder.RecordRoundStartedRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.supplier_ = supplier_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gameType_ = gameType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gameSubtype_ = gameSubtype_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gameVersion_ = gameVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gameCode_ = gameCode_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tableCode_ = tableCode_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.shiftCode_ = shiftCode_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.shiftRound_ = shiftRound_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.shoeCode_ = shoeCode_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.shoeRound_ = shoeRound_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.roundCode_ = roundCode_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.tsStart_ = tsStartBuilder_ == null
            ? tsStart_
            : tsStartBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.players_ = internalGetPlayers();
        result.players_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.playersName_ = internalGetPlayersName();
        result.playersName_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wecasino.proto.recorder.RecordRoundStartedRequest) {
        return mergeFrom((com.wecasino.proto.recorder.RecordRoundStartedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wecasino.proto.recorder.RecordRoundStartedRequest other) {
      if (other == com.wecasino.proto.recorder.RecordRoundStartedRequest.getDefaultInstance()) return this;
      if (!other.getSupplier().isEmpty()) {
        supplier_ = other.supplier_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGameType().isEmpty()) {
        gameType_ = other.gameType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getGameSubtype().isEmpty()) {
        gameSubtype_ = other.gameSubtype_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getGameVersion().isEmpty()) {
        gameVersion_ = other.gameVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getGameCode().isEmpty()) {
        gameCode_ = other.gameCode_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTableCode().isEmpty()) {
        tableCode_ = other.tableCode_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getShiftCode().isEmpty()) {
        shiftCode_ = other.shiftCode_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getShiftRound() != 0L) {
        setShiftRound(other.getShiftRound());
      }
      if (!other.getShoeCode().isEmpty()) {
        shoeCode_ = other.shoeCode_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getShoeRound() != 0L) {
        setShoeRound(other.getShoeRound());
      }
      if (!other.getRoundCode().isEmpty()) {
        roundCode_ = other.roundCode_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      bitField0_ |= 0x00000800;
      if (other.hasTsStart()) {
        mergeTsStart(other.getTsStart());
      }
      internalGetMutablePlayers().mergeFrom(
          other.internalGetPlayers());
      bitField0_ |= 0x00002000;
      internalGetMutablePlayersName().mergeFrom(
          other.internalGetPlayersName());
      bitField0_ |= 0x00004000;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              supplier_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            case 26: {
              gameType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 34: {
              gameSubtype_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            case 42: {
              gameVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            case 50: {
              gameCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 50
            case 58: {
              tableCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 58
            case 66: {
              shiftCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 66
            case 72: {
              shiftRound_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 72
            case 82: {
              shoeCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 82
            case 88: {
              shoeRound_ = input.readInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 88
            case 98: {
              roundCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 98
            case 106: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTags().getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              bitField0_ |= 0x00000800;
              break;
            } // case 106
            case 130: {
              input.readMessage(
                  getTsStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 130
            case 202: {
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              players__ = input.readMessage(
                  PlayersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePlayers().getMutableMap().put(
                  players__.getKey(), players__.getValue());
              bitField0_ |= 0x00002000;
              break;
            } // case 202
            case 242: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              playersName__ = input.readMessage(
                  PlayersNameDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePlayersName().getMutableMap().put(
                  playersName__.getKey(), playersName__.getValue());
              bitField0_ |= 0x00004000;
              break;
            } // case 242
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object supplier_ = "";
    /**
     * <pre>
     * 遊戲供應
     * </pre>
     *
     * <code>string supplier = 2 [json_name = "supplier"];</code>
     * @return The supplier.
     */
    public java.lang.String getSupplier() {
      java.lang.Object ref = supplier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        supplier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 遊戲供應
     * </pre>
     *
     * <code>string supplier = 2 [json_name = "supplier"];</code>
     * @return The bytes for supplier.
     */
    public com.google.protobuf.ByteString
        getSupplierBytes() {
      java.lang.Object ref = supplier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        supplier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 遊戲供應
     * </pre>
     *
     * <code>string supplier = 2 [json_name = "supplier"];</code>
     * @param value The supplier to set.
     * @return This builder for chaining.
     */
    public Builder setSupplier(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      supplier_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲供應
     * </pre>
     *
     * <code>string supplier = 2 [json_name = "supplier"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSupplier() {
      supplier_ = getDefaultInstance().getSupplier();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲供應
     * </pre>
     *
     * <code>string supplier = 2 [json_name = "supplier"];</code>
     * @param value The bytes for supplier to set.
     * @return This builder for chaining.
     */
    public Builder setSupplierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      supplier_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object gameType_ = "";
    /**
     * <pre>
     * 遊戲類型
     * </pre>
     *
     * <code>string game_type = 3 [json_name = "gameType"];</code>
     * @return The gameType.
     */
    public java.lang.String getGameType() {
      java.lang.Object ref = gameType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 遊戲類型
     * </pre>
     *
     * <code>string game_type = 3 [json_name = "gameType"];</code>
     * @return The bytes for gameType.
     */
    public com.google.protobuf.ByteString
        getGameTypeBytes() {
      java.lang.Object ref = gameType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 遊戲類型
     * </pre>
     *
     * <code>string game_type = 3 [json_name = "gameType"];</code>
     * @param value The gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲類型
     * </pre>
     *
     * <code>string game_type = 3 [json_name = "gameType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameType() {
      gameType_ = getDefaultInstance().getGameType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲類型
     * </pre>
     *
     * <code>string game_type = 3 [json_name = "gameType"];</code>
     * @param value The bytes for gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object gameSubtype_ = "";
    /**
     * <pre>
     * 遊戲子類型
     * </pre>
     *
     * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
     * @return The gameSubtype.
     */
    public java.lang.String getGameSubtype() {
      java.lang.Object ref = gameSubtype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameSubtype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 遊戲子類型
     * </pre>
     *
     * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
     * @return The bytes for gameSubtype.
     */
    public com.google.protobuf.ByteString
        getGameSubtypeBytes() {
      java.lang.Object ref = gameSubtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameSubtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 遊戲子類型
     * </pre>
     *
     * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
     * @param value The gameSubtype to set.
     * @return This builder for chaining.
     */
    public Builder setGameSubtype(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameSubtype_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲子類型
     * </pre>
     *
     * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameSubtype() {
      gameSubtype_ = getDefaultInstance().getGameSubtype();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲子類型
     * </pre>
     *
     * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
     * @param value The bytes for gameSubtype to set.
     * @return This builder for chaining.
     */
    public Builder setGameSubtypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameSubtype_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object gameVersion_ = "";
    /**
     * <pre>
     * 遊戲版本
     * </pre>
     *
     * <code>string game_version = 5 [json_name = "gameVersion"];</code>
     * @return The gameVersion.
     */
    public java.lang.String getGameVersion() {
      java.lang.Object ref = gameVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 遊戲版本
     * </pre>
     *
     * <code>string game_version = 5 [json_name = "gameVersion"];</code>
     * @return The bytes for gameVersion.
     */
    public com.google.protobuf.ByteString
        getGameVersionBytes() {
      java.lang.Object ref = gameVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 遊戲版本
     * </pre>
     *
     * <code>string game_version = 5 [json_name = "gameVersion"];</code>
     * @param value The gameVersion to set.
     * @return This builder for chaining.
     */
    public Builder setGameVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲版本
     * </pre>
     *
     * <code>string game_version = 5 [json_name = "gameVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameVersion() {
      gameVersion_ = getDefaultInstance().getGameVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲版本
     * </pre>
     *
     * <code>string game_version = 5 [json_name = "gameVersion"];</code>
     * @param value The bytes for gameVersion to set.
     * @return This builder for chaining.
     */
    public Builder setGameVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object gameCode_ = "";
    /**
     * <pre>
     * 遊戲代碼
     * </pre>
     *
     * <code>string game_code = 6 [json_name = "gameCode"];</code>
     * @return The gameCode.
     */
    public java.lang.String getGameCode() {
      java.lang.Object ref = gameCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 遊戲代碼
     * </pre>
     *
     * <code>string game_code = 6 [json_name = "gameCode"];</code>
     * @return The bytes for gameCode.
     */
    public com.google.protobuf.ByteString
        getGameCodeBytes() {
      java.lang.Object ref = gameCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 遊戲代碼
     * </pre>
     *
     * <code>string game_code = 6 [json_name = "gameCode"];</code>
     * @param value The gameCode to set.
     * @return This builder for chaining.
     */
    public Builder setGameCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲代碼
     * </pre>
     *
     * <code>string game_code = 6 [json_name = "gameCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameCode() {
      gameCode_ = getDefaultInstance().getGameCode();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 遊戲代碼
     * </pre>
     *
     * <code>string game_code = 6 [json_name = "gameCode"];</code>
     * @param value The bytes for gameCode to set.
     * @return This builder for chaining.
     */
    public Builder setGameCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gameCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object tableCode_ = "";
    /**
     * <pre>
     * 桌代碼
     * </pre>
     *
     * <code>string table_code = 7 [json_name = "tableCode"];</code>
     * @return The tableCode.
     */
    public java.lang.String getTableCode() {
      java.lang.Object ref = tableCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 桌代碼
     * </pre>
     *
     * <code>string table_code = 7 [json_name = "tableCode"];</code>
     * @return The bytes for tableCode.
     */
    public com.google.protobuf.ByteString
        getTableCodeBytes() {
      java.lang.Object ref = tableCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 桌代碼
     * </pre>
     *
     * <code>string table_code = 7 [json_name = "tableCode"];</code>
     * @param value The tableCode to set.
     * @return This builder for chaining.
     */
    public Builder setTableCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableCode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 桌代碼
     * </pre>
     *
     * <code>string table_code = 7 [json_name = "tableCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTableCode() {
      tableCode_ = getDefaultInstance().getTableCode();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 桌代碼
     * </pre>
     *
     * <code>string table_code = 7 [json_name = "tableCode"];</code>
     * @param value The bytes for tableCode to set.
     * @return This builder for chaining.
     */
    public Builder setTableCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableCode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object shiftCode_ = "";
    /**
     * <pre>
     * 班代碼
     * </pre>
     *
     * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
     * @return The shiftCode.
     */
    public java.lang.String getShiftCode() {
      java.lang.Object ref = shiftCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shiftCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 班代碼
     * </pre>
     *
     * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
     * @return The bytes for shiftCode.
     */
    public com.google.protobuf.ByteString
        getShiftCodeBytes() {
      java.lang.Object ref = shiftCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shiftCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 班代碼
     * </pre>
     *
     * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
     * @param value The shiftCode to set.
     * @return This builder for chaining.
     */
    public Builder setShiftCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      shiftCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班代碼
     * </pre>
     *
     * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearShiftCode() {
      shiftCode_ = getDefaultInstance().getShiftCode();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班代碼
     * </pre>
     *
     * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
     * @param value The bytes for shiftCode to set.
     * @return This builder for chaining.
     */
    public Builder setShiftCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      shiftCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long shiftRound_ ;
    /**
     * <pre>
     * 此排班局數
     * </pre>
     *
     * <code>int64 shift_round = 9 [json_name = "shiftRound"];</code>
     * @return The shiftRound.
     */
    @java.lang.Override
    public long getShiftRound() {
      return shiftRound_;
    }
    /**
     * <pre>
     * 此排班局數
     * </pre>
     *
     * <code>int64 shift_round = 9 [json_name = "shiftRound"];</code>
     * @param value The shiftRound to set.
     * @return This builder for chaining.
     */
    public Builder setShiftRound(long value) {

      shiftRound_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 此排班局數
     * </pre>
     *
     * <code>int64 shift_round = 9 [json_name = "shiftRound"];</code>
     * @return This builder for chaining.
     */
    public Builder clearShiftRound() {
      bitField0_ = (bitField0_ & ~0x00000080);
      shiftRound_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object shoeCode_ = "";
    /**
     * <pre>
     * 使用洗牌代碼
     * </pre>
     *
     * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
     * @return The shoeCode.
     */
    public java.lang.String getShoeCode() {
      java.lang.Object ref = shoeCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shoeCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 使用洗牌代碼
     * </pre>
     *
     * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
     * @return The bytes for shoeCode.
     */
    public com.google.protobuf.ByteString
        getShoeCodeBytes() {
      java.lang.Object ref = shoeCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shoeCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 使用洗牌代碼
     * </pre>
     *
     * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
     * @param value The shoeCode to set.
     * @return This builder for chaining.
     */
    public Builder setShoeCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      shoeCode_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用洗牌代碼
     * </pre>
     *
     * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearShoeCode() {
      shoeCode_ = getDefaultInstance().getShoeCode();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用洗牌代碼
     * </pre>
     *
     * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
     * @param value The bytes for shoeCode to set.
     * @return This builder for chaining.
     */
    public Builder setShoeCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      shoeCode_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private long shoeRound_ ;
    /**
     * <pre>
     * 使用此洗牌第幾局，從1開始計算
     * </pre>
     *
     * <code>int64 shoe_round = 11 [json_name = "shoeRound"];</code>
     * @return The shoeRound.
     */
    @java.lang.Override
    public long getShoeRound() {
      return shoeRound_;
    }
    /**
     * <pre>
     * 使用此洗牌第幾局，從1開始計算
     * </pre>
     *
     * <code>int64 shoe_round = 11 [json_name = "shoeRound"];</code>
     * @param value The shoeRound to set.
     * @return This builder for chaining.
     */
    public Builder setShoeRound(long value) {

      shoeRound_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用此洗牌第幾局，從1開始計算
     * </pre>
     *
     * <code>int64 shoe_round = 11 [json_name = "shoeRound"];</code>
     * @return This builder for chaining.
     */
    public Builder clearShoeRound() {
      bitField0_ = (bitField0_ & ~0x00000200);
      shoeRound_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object roundCode_ = "";
    /**
     * <pre>
     * 局代碼
     * </pre>
     *
     * <code>string round_code = 12 [json_name = "roundCode"];</code>
     * @return The roundCode.
     */
    public java.lang.String getRoundCode() {
      java.lang.Object ref = roundCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roundCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 局代碼
     * </pre>
     *
     * <code>string round_code = 12 [json_name = "roundCode"];</code>
     * @return The bytes for roundCode.
     */
    public com.google.protobuf.ByteString
        getRoundCodeBytes() {
      java.lang.Object ref = roundCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roundCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 局代碼
     * </pre>
     *
     * <code>string round_code = 12 [json_name = "roundCode"];</code>
     * @param value The roundCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoundCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roundCode_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 局代碼
     * </pre>
     *
     * <code>string round_code = 12 [json_name = "roundCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundCode() {
      roundCode_ = getDefaultInstance().getRoundCode();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 局代碼
     * </pre>
     *
     * <code>string round_code = 12 [json_name = "roundCode"];</code>
     * @param value The bytes for roundCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoundCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roundCode_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableTags() {
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return tags_;
    }
    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getTagsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    @java.lang.Override
    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearTags() {
      bitField0_ = (bitField0_ & ~0x00000800);
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableTags() {
      bitField0_ |= 0x00000800;
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTags().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <pre>
     * 標籤
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 13 [json_name = "tags"];</code>
     */
    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000800;
      return this;
    }

    private com.google.protobuf.Timestamp tsStart_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> tsStartBuilder_;
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     * @return Whether the tsStart field is set.
     */
    public boolean hasTsStart() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     * @return The tsStart.
     */
    public com.google.protobuf.Timestamp getTsStart() {
      if (tsStartBuilder_ == null) {
        return tsStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : tsStart_;
      } else {
        return tsStartBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public Builder setTsStart(com.google.protobuf.Timestamp value) {
      if (tsStartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tsStart_ = value;
      } else {
        tsStartBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public Builder setTsStart(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (tsStartBuilder_ == null) {
        tsStart_ = builderForValue.build();
      } else {
        tsStartBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public Builder mergeTsStart(com.google.protobuf.Timestamp value) {
      if (tsStartBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          tsStart_ != null &&
          tsStart_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTsStartBuilder().mergeFrom(value);
        } else {
          tsStart_ = value;
        }
      } else {
        tsStartBuilder_.mergeFrom(value);
      }
      if (tsStart_ != null) {
        bitField0_ |= 0x00001000;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public Builder clearTsStart() {
      bitField0_ = (bitField0_ & ~0x00001000);
      tsStart_ = null;
      if (tsStartBuilder_ != null) {
        tsStartBuilder_.dispose();
        tsStartBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTsStartBuilder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return getTsStartFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTsStartOrBuilder() {
      if (tsStartBuilder_ != null) {
        return tsStartBuilder_.getMessageOrBuilder();
      } else {
        return tsStart_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : tsStart_;
      }
    }
    /**
     * <pre>
     * 開始時間
     * </pre>
     *
     * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTsStartFieldBuilder() {
      if (tsStartBuilder_ == null) {
        tsStartBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTsStart(),
                getParentForChildren(),
                isClean());
        tsStart_ = null;
      }
      return tsStartBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> players_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
        internalGetPlayers() {
      if (players_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PlayersDefaultEntryHolder.defaultEntry);
      }
      return players_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
        internalGetMutablePlayers() {
      if (players_ == null) {
        players_ = com.google.protobuf.MapField.newMapField(
            PlayersDefaultEntryHolder.defaultEntry);
      }
      if (!players_.isMutable()) {
        players_ = players_.copy();
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return players_;
    }
    public int getPlayersCount() {
      return internalGetPlayers().getMap().size();
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    @java.lang.Override
    public boolean containsPlayers(
        int key) {

      return internalGetPlayers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPlayersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getPlayers() {
      return getPlayersMap();
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.String> getPlayersMap() {
      return internalGetPlayers().getMap();
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getPlayersOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetPlayers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    @java.lang.Override
    public java.lang.String getPlayersOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetPlayers().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00002000);
      internalGetMutablePlayers().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    public Builder removePlayers(
        int key) {

      internalGetMutablePlayers().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String>
        getMutablePlayers() {
      bitField0_ |= 0x00002000;
      return internalGetMutablePlayers().getMutableMap();
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    public Builder putPlayers(
        int key,
        java.lang.String value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePlayers().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00002000;
      return this;
    }
    /**
     * <pre>
     * 玩家入座
     * </pre>
     *
     * <code>map&lt;int32, string&gt; players = 25 [json_name = "players"];</code>
     */
    public Builder putAllPlayers(
        java.util.Map<java.lang.Integer, java.lang.String> values) {
      internalGetMutablePlayers().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00002000;
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> playersName_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetPlayersName() {
      if (playersName_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PlayersNameDefaultEntryHolder.defaultEntry);
      }
      return playersName_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutablePlayersName() {
      if (playersName_ == null) {
        playersName_ = com.google.protobuf.MapField.newMapField(
            PlayersNameDefaultEntryHolder.defaultEntry);
      }
      if (!playersName_.isMutable()) {
        playersName_ = playersName_.copy();
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return playersName_;
    }
    public int getPlayersNameCount() {
      return internalGetPlayersName().getMap().size();
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    @java.lang.Override
    public boolean containsPlayersName(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPlayersName().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPlayersNameMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getPlayersName() {
      return getPlayersNameMap();
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getPlayersNameMap() {
      return internalGetPlayersName().getMap();
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getPlayersNameOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPlayersName().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    @java.lang.Override
    public java.lang.String getPlayersNameOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPlayersName().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearPlayersName() {
      bitField0_ = (bitField0_ & ~0x00004000);
      internalGetMutablePlayersName().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    public Builder removePlayersName(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePlayersName().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutablePlayersName() {
      bitField0_ |= 0x00004000;
      return internalGetMutablePlayersName().getMutableMap();
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    public Builder putPlayersName(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePlayersName().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00004000;
      return this;
    }
    /**
     * <pre>
     * 玩家姓名
     * </pre>
     *
     * <code>map&lt;string, string&gt; players_name = 30 [json_name = "playersName"];</code>
     */
    public Builder putAllPlayersName(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutablePlayersName().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00004000;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:recorder.RecordRoundStartedRequest)
  }

  // @@protoc_insertion_point(class_scope:recorder.RecordRoundStartedRequest)
  private static final com.wecasino.proto.recorder.RecordRoundStartedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wecasino.proto.recorder.RecordRoundStartedRequest();
  }

  public static com.wecasino.proto.recorder.RecordRoundStartedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordRoundStartedRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecordRoundStartedRequest>() {
    @java.lang.Override
    public RecordRoundStartedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordRoundStartedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordRoundStartedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wecasino.proto.recorder.RecordRoundStartedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

