// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/recorder.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

public interface RecordShoeStartedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.RecordShoeStartedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 遊戲供應
   * </pre>
   *
   * <code>string supplier = 2 [json_name = "supplier"];</code>
   * @return The supplier.
   */
  java.lang.String getSupplier();
  /**
   * <pre>
   * 遊戲供應
   * </pre>
   *
   * <code>string supplier = 2 [json_name = "supplier"];</code>
   * @return The bytes for supplier.
   */
  com.google.protobuf.ByteString
      getSupplierBytes();

  /**
   * <pre>
   * 遊戲類型
   * </pre>
   *
   * <code>string game_type = 3 [json_name = "gameType"];</code>
   * @return The gameType.
   */
  java.lang.String getGameType();
  /**
   * <pre>
   * 遊戲類型
   * </pre>
   *
   * <code>string game_type = 3 [json_name = "gameType"];</code>
   * @return The bytes for gameType.
   */
  com.google.protobuf.ByteString
      getGameTypeBytes();

  /**
   * <pre>
   * 遊戲子類型
   * </pre>
   *
   * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
   * @return The gameSubtype.
   */
  java.lang.String getGameSubtype();
  /**
   * <pre>
   * 遊戲子類型
   * </pre>
   *
   * <code>string game_subtype = 4 [json_name = "gameSubtype"];</code>
   * @return The bytes for gameSubtype.
   */
  com.google.protobuf.ByteString
      getGameSubtypeBytes();

  /**
   * <pre>
   * 遊戲版本
   * </pre>
   *
   * <code>string game_version = 5 [json_name = "gameVersion"];</code>
   * @return The gameVersion.
   */
  java.lang.String getGameVersion();
  /**
   * <pre>
   * 遊戲版本
   * </pre>
   *
   * <code>string game_version = 5 [json_name = "gameVersion"];</code>
   * @return The bytes for gameVersion.
   */
  com.google.protobuf.ByteString
      getGameVersionBytes();

  /**
   * <pre>
   * 遊戲代碼
   * </pre>
   *
   * <code>string game_code = 6 [json_name = "gameCode"];</code>
   * @return The gameCode.
   */
  java.lang.String getGameCode();
  /**
   * <pre>
   * 遊戲代碼
   * </pre>
   *
   * <code>string game_code = 6 [json_name = "gameCode"];</code>
   * @return The bytes for gameCode.
   */
  com.google.protobuf.ByteString
      getGameCodeBytes();

  /**
   * <pre>
   * 桌代碼
   * </pre>
   *
   * <code>string table_code = 7 [json_name = "tableCode"];</code>
   * @return The tableCode.
   */
  java.lang.String getTableCode();
  /**
   * <pre>
   * 桌代碼
   * </pre>
   *
   * <code>string table_code = 7 [json_name = "tableCode"];</code>
   * @return The bytes for tableCode.
   */
  com.google.protobuf.ByteString
      getTableCodeBytes();

  /**
   * <pre>
   * 班代碼
   * </pre>
   *
   * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
   * @return The shiftCode.
   */
  java.lang.String getShiftCode();
  /**
   * <pre>
   * 班代碼
   * </pre>
   *
   * <code>string shift_code = 8 [json_name = "shiftCode"];</code>
   * @return The bytes for shiftCode.
   */
  com.google.protobuf.ByteString
      getShiftCodeBytes();

  /**
   * <pre>
   * 使用洗牌代碼
   * </pre>
   *
   * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
   * @return The shoeCode.
   */
  java.lang.String getShoeCode();
  /**
   * <pre>
   * 使用洗牌代碼
   * </pre>
   *
   * <code>string shoe_code = 10 [json_name = "shoeCode"];</code>
   * @return The bytes for shoeCode.
   */
  com.google.protobuf.ByteString
      getShoeCodeBytes();

  /**
   * <pre>
   * 此牌靴開始使用時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   * @return Whether the tsStart field is set.
   */
  boolean hasTsStart();
  /**
   * <pre>
   * 此牌靴開始使用時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   * @return The tsStart.
   */
  com.google.protobuf.Timestamp getTsStart();
  /**
   * <pre>
   * 此牌靴開始使用時間
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_start = 16 [json_name = "tsStart"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTsStartOrBuilder();

  /**
   * <pre>
   * cardList
   * </pre>
   *
   * <code>map&lt;int32, .recorder.Deck&gt; decks = 24 [json_name = "decks"];</code>
   */
  int getDecksCount();
  /**
   * <pre>
   * cardList
   * </pre>
   *
   * <code>map&lt;int32, .recorder.Deck&gt; decks = 24 [json_name = "decks"];</code>
   */
  boolean containsDecks(
      int key);
  /**
   * Use {@link #getDecksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.wecasino.proto.recorder.Deck>
  getDecks();
  /**
   * <pre>
   * cardList
   * </pre>
   *
   * <code>map&lt;int32, .recorder.Deck&gt; decks = 24 [json_name = "decks"];</code>
   */
  java.util.Map<java.lang.Integer, com.wecasino.proto.recorder.Deck>
  getDecksMap();
  /**
   * <pre>
   * cardList
   * </pre>
   *
   * <code>map&lt;int32, .recorder.Deck&gt; decks = 24 [json_name = "decks"];</code>
   */
  /* nullable */
com.wecasino.proto.recorder.Deck getDecksOrDefault(
      int key,
      /* nullable */
com.wecasino.proto.recorder.Deck defaultValue);
  /**
   * <pre>
   * cardList
   * </pre>
   *
   * <code>map&lt;int32, .recorder.Deck&gt; decks = 24 [json_name = "decks"];</code>
   */
  com.wecasino.proto.recorder.Deck getDecksOrThrow(
      int key);
}
