// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recorder/provider.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.recorder;

public interface RecordQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder.RecordQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 查詢起時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_from = 1 [json_name = "tsFrom"];</code>
   * @return Whether the tsFrom field is set.
   */
  boolean hasTsFrom();
  /**
   * <pre>
   * 查詢起時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_from = 1 [json_name = "tsFrom"];</code>
   * @return The tsFrom.
   */
  com.google.protobuf.Timestamp getTsFrom();
  /**
   * <pre>
   * 查詢起時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_from = 1 [json_name = "tsFrom"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTsFromOrBuilder();

  /**
   * <pre>
   * 查詢終時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_to = 2 [json_name = "tsTo"];</code>
   * @return Whether the tsTo field is set.
   */
  boolean hasTsTo();
  /**
   * <pre>
   * 查詢終時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_to = 2 [json_name = "tsTo"];</code>
   * @return The tsTo.
   */
  com.google.protobuf.Timestamp getTsTo();
  /**
   * <pre>
   * 查詢終時
   * </pre>
   *
   * <code>.google.protobuf.Timestamp ts_to = 2 [json_name = "tsTo"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTsToOrBuilder();

  /**
   * <pre>
   * 筆數 預設 100
   * </pre>
   *
   * <code>optional int64 limit = 3 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <pre>
   * 筆數 預設 100
   * </pre>
   *
   * <code>optional int64 limit = 3 [json_name = "limit"];</code>
   * @return The limit.
   */
  long getLimit();

  /**
   * <pre>
   * 頁面
   * </pre>
   *
   * <code>optional int64 page = 4 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <pre>
   * 頁面
   * </pre>
   *
   * <code>optional int64 page = 4 [json_name = "page"];</code>
   * @return The page.
   */
  long getPage();
}
