syntax = "proto3";
package games.baccaratstep;

enum GameSubtype {
  // 未指定
  BACCARAT_TYPE_UNSPECIFIED = 0;
  // deprecated 看牌百家樂向下相容使用
  BACCARAT_CLASSIC = 1;
  // 看牌百家樂
  BACCARAT_STEP = 2;
}

enum ResourceType {

  // 未指定
  RESOURCE_TYPE_UNSPECIFIED = 0;

  // 例牌
  NORMAL = 1;

  // 非例牌
  EXTRA = 2;

}

// 步驟，依據遊戲供應商邏輯，不是每個步驟都會走到
enum Step {

  // 未指定
  STEP_UNSPECIFIED = 0;
  // 本局開始
  ROUND_START = 1;
  // 本局完成
  ROUND_FINISHED = 2;
  // 展示第一張牌
  SHOW_FIRST_CARD = 3;

  // 派發閒家例牌1
  DEAL_PLAYER_1 = 4;
  // 派發莊家例牌1
  DEAL_BANKER_1 = 5;
  // 派發閒家例牌2
  DEAL_PLAYER_2 = 6;
  // 派發莊家例牌2
  DEAL_BANKER_2 = 7;

  // 開放下注
  ROUND_BET = 8;
  // 停止下注
  NO_MORE_BET = 9;

  // 開例牌
  SHOW_NORMAL = 11;

  // 開剩下的例牌
  SHOW_LEFT = 12;

  // 開 莊牌
  SHOW_BANKER_1 = 30;
  // 開 莊牌
  SHOW_BANKER_2 = 31;

  // 開 閒牌
  SHOW_PLAYER_1 = 33;
  // 開 閒牌
  SHOW_PLAYER_2 = 34;

  // 補閒家牌
  DEAL_PLAYER_EXTRA = 16;

  // 補莊家牌
  DEAL_BANKER_EXTRA = 20;

  DEALER_CONFIRM = 23;

  // PITBOSS 修改派發例牌
  PITBOSS_MODIFY_NORMAL = 24;
  // PITBOSS 修改派發閒家補牌
  PITBOSS_MODIFY_PLAYER_EXTRA = 25;
  // PITBOSS 修改派發莊家補牌
  PITBOSS_MODIFY_BANKER_EXTRA = 26;

  // 二階段看牌百家樂開始
  SECOND_ROUND_START = 39;
  // 二階段看牌百家樂開放下注
  SECOND_ROUND_BET = 40;
  // 二階段看牌百家樂停止下注
  SECOND_NO_MORE_BET = 41;
}

// 座位功能代碼
enum GameSeat {

  // 未指定
  SEAT_UNSPECIFIED = 0;
  // 閒家
  PLAYER = 2;
  // 莊家
  BANKER = 3;

}
