// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: games/color/record.proto

package color

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GamblerInstructionType int32

const (
	// 未指定
	GamblerInstructionType_GAMBLER_INSTRUCTION_UNSPECIFIED GamblerInstructionType = 0
	// 左側骰子
	GamblerInstructionType_LEFT_UP GamblerInstructionType = 1
	// 中間骰子
	GamblerInstructionType_MIDDLE_UP GamblerInstructionType = 2
	// 右邊骰子
	GamblerInstructionType_RIGHT_UP GamblerInstructionType = 3
)

// Enum value maps for GamblerInstructionType.
var (
	GamblerInstructionType_name = map[int32]string{
		0: "GAMBLER_INSTRUCTION_UNSPECIFIED",
		1: "LEFT_UP",
		2: "MIDDLE_UP",
		3: "RIGHT_UP",
	}
	GamblerInstructionType_value = map[string]int32{
		"GAMBLER_INSTRUCTION_UNSPECIFIED": 0,
		"LEFT_UP":                         1,
		"MIDDLE_UP":                       2,
		"RIGHT_UP":                        3,
	}
)

func (x GamblerInstructionType) Enum() *GamblerInstructionType {
	p := new(GamblerInstructionType)
	*p = x
	return p
}

func (x GamblerInstructionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamblerInstructionType) Descriptor() protoreflect.EnumDescriptor {
	return file_games_color_record_proto_enumTypes[0].Descriptor()
}

func (GamblerInstructionType) Type() protoreflect.EnumType {
	return &file_games_color_record_proto_enumTypes[0]
}

func (x GamblerInstructionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamblerInstructionType.Descriptor instead.
func (GamblerInstructionType) EnumDescriptor() ([]byte, []int) {
	return file_games_color_record_proto_rawDescGZIP(), []int{0}
}

type GameSubtype int32

const (
	// 未指定
	GameSubtype_COLOR_TYPE_UNSPECIFIED GameSubtype = 0
	// color
	GameSubtype_COLOR_CLASSIC GameSubtype = 1
	// color_mini
	GameSubtype_COLOR_MINI GameSubtype = 2
	// 區塊鏈color
	GameSubtype_COLOR_BLOCKCHAIN GameSubtype = 16
)

// Enum value maps for GameSubtype.
var (
	GameSubtype_name = map[int32]string{
		0:  "COLOR_TYPE_UNSPECIFIED",
		1:  "COLOR_CLASSIC",
		2:  "COLOR_MINI",
		16: "COLOR_BLOCKCHAIN",
	}
	GameSubtype_value = map[string]int32{
		"COLOR_TYPE_UNSPECIFIED": 0,
		"COLOR_CLASSIC":          1,
		"COLOR_MINI":             2,
		"COLOR_BLOCKCHAIN":       16,
	}
)

func (x GameSubtype) Enum() *GameSubtype {
	p := new(GameSubtype)
	*p = x
	return p
}

func (x GameSubtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSubtype) Descriptor() protoreflect.EnumDescriptor {
	return file_games_color_record_proto_enumTypes[1].Descriptor()
}

func (GameSubtype) Type() protoreflect.EnumType {
	return &file_games_color_record_proto_enumTypes[1]
}

func (x GameSubtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSubtype.Descriptor instead.
func (GameSubtype) EnumDescriptor() ([]byte, []int) {
	return file_games_color_record_proto_rawDescGZIP(), []int{1}
}

// 步驟，依據遊戲供應商邏輯，不是每個步驟都會走到
type Step int32

const (
	// 未指定
	Step_STEP_UNSPECIFIED Step = 0
	// 本局開始
	Step_ROUND_START Step = 1
	// 本局完成
	Step_ROUND_FINISHED Step = 2
	// 本局取消
	Step_ROUND_CANCELED Step = 3
	// 開放下注
	Step_ROUND_BET Step = 4
	// 停止下注
	Step_NO_MORE_BET Step = 5
	// 擲骰
	Step_THROW_COLOR Step = 8
	// SUPER_GAME
	Step_SUPER_GAME_ROUND_READY Step = 9
	// 開始
	Step_SUPER_GAME_ROUND_START Step = 10
	// 開放下注
	Step_SUPER_GAME_ROUND_BET Step = 11
	// 停止下注
	Step_SUPER_GAME_NO_MORE_BET Step = 12
	Step_SUPER_GAME_THROW_COLOR Step = 13
	// PITBOSS 修改骰點
	Step_PITBOSS_MODIFY_BOWL Step = 16
)

// Enum value maps for Step.
var (
	Step_name = map[int32]string{
		0:  "STEP_UNSPECIFIED",
		1:  "ROUND_START",
		2:  "ROUND_FINISHED",
		3:  "ROUND_CANCELED",
		4:  "ROUND_BET",
		5:  "NO_MORE_BET",
		8:  "THROW_COLOR",
		9:  "SUPER_GAME_ROUND_READY",
		10: "SUPER_GAME_ROUND_START",
		11: "SUPER_GAME_ROUND_BET",
		12: "SUPER_GAME_NO_MORE_BET",
		13: "SUPER_GAME_THROW_COLOR",
		16: "PITBOSS_MODIFY_BOWL",
	}
	Step_value = map[string]int32{
		"STEP_UNSPECIFIED":       0,
		"ROUND_START":            1,
		"ROUND_FINISHED":         2,
		"ROUND_CANCELED":         3,
		"ROUND_BET":              4,
		"NO_MORE_BET":            5,
		"THROW_COLOR":            8,
		"SUPER_GAME_ROUND_READY": 9,
		"SUPER_GAME_ROUND_START": 10,
		"SUPER_GAME_ROUND_BET":   11,
		"SUPER_GAME_NO_MORE_BET": 12,
		"SUPER_GAME_THROW_COLOR": 13,
		"PITBOSS_MODIFY_BOWL":    16,
	}
)

func (x Step) Enum() *Step {
	p := new(Step)
	*p = x
	return p
}

func (x Step) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Step) Descriptor() protoreflect.EnumDescriptor {
	return file_games_color_record_proto_enumTypes[2].Descriptor()
}

func (Step) Type() protoreflect.EnumType {
	return &file_games_color_record_proto_enumTypes[2]
}

func (x Step) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Step.Descriptor instead.
func (Step) EnumDescriptor() ([]byte, []int) {
	return file_games_color_record_proto_rawDescGZIP(), []int{2}
}

type ResourceType int32

const (
	// 未指定
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	// 一般
	ResourceType_NORMAL ResourceType = 1
	// SUPER GAME
	ResourceType_SUPER_GAME ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "NORMAL",
		2: "SUPER_GAME",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"NORMAL":                    1,
		"SUPER_GAME":                2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_games_color_record_proto_enumTypes[3].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_games_color_record_proto_enumTypes[3]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_games_color_record_proto_rawDescGZIP(), []int{3}
}

var File_games_color_record_proto protoreflect.FileDescriptor

const file_games_color_record_proto_rawDesc = "" +
	"\n" +
	"\x18games/color/record.proto\x12\vgames.color*g\n" +
	"\x16GamblerInstructionType\x12#\n" +
	"\x1fGAMBLER_INSTRUCTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aLEFT_UP\x10\x01\x12\r\n" +
	"\tMIDDLE_UP\x10\x02\x12\f\n" +
	"\bRIGHT_UP\x10\x03*b\n" +
	"\vGameSubtype\x12\x1a\n" +
	"\x16COLOR_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCOLOR_CLASSIC\x10\x01\x12\x0e\n" +
	"\n" +
	"COLOR_MINI\x10\x02\x12\x14\n" +
	"\x10COLOR_BLOCKCHAIN\x10\x10*\xa9\x02\n" +
	"\x04Step\x12\x14\n" +
	"\x10STEP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROUND_START\x10\x01\x12\x12\n" +
	"\x0eROUND_FINISHED\x10\x02\x12\x12\n" +
	"\x0eROUND_CANCELED\x10\x03\x12\r\n" +
	"\tROUND_BET\x10\x04\x12\x0f\n" +
	"\vNO_MORE_BET\x10\x05\x12\x0f\n" +
	"\vTHROW_COLOR\x10\b\x12\x1a\n" +
	"\x16SUPER_GAME_ROUND_READY\x10\t\x12\x1a\n" +
	"\x16SUPER_GAME_ROUND_START\x10\n" +
	"\x12\x18\n" +
	"\x14SUPER_GAME_ROUND_BET\x10\v\x12\x1a\n" +
	"\x16SUPER_GAME_NO_MORE_BET\x10\f\x12\x1a\n" +
	"\x16SUPER_GAME_THROW_COLOR\x10\r\x12\x17\n" +
	"\x13PITBOSS_MODIFY_BOWL\x10\x10*I\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\x0e\n" +
	"\n" +
	"SUPER_GAME\x10\x02B\xaf\x01\n" +
	"\x1ecom.wecasino.proto.games.colorB\vRecordProtoP\x01Z3github.com/wecasino/wecasino-proto/pbgo/games/color\xa2\x02\x03GCX\xaa\x02\vGames.Color\xca\x02\vGames\\Color\xe2\x02\x17Games\\Color\\GPBMetadata\xea\x02\fGames::Colorb\x06proto3"

var (
	file_games_color_record_proto_rawDescOnce sync.Once
	file_games_color_record_proto_rawDescData []byte
)

func file_games_color_record_proto_rawDescGZIP() []byte {
	file_games_color_record_proto_rawDescOnce.Do(func() {
		file_games_color_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_games_color_record_proto_rawDesc), len(file_games_color_record_proto_rawDesc)))
	})
	return file_games_color_record_proto_rawDescData
}

var file_games_color_record_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_games_color_record_proto_goTypes = []any{
	(GamblerInstructionType)(0), // 0: games.color.GamblerInstructionType
	(GameSubtype)(0),            // 1: games.color.GameSubtype
	(Step)(0),                   // 2: games.color.Step
	(ResourceType)(0),           // 3: games.color.ResourceType
}
var file_games_color_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_games_color_record_proto_init() }
func file_games_color_record_proto_init() {
	if File_games_color_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_games_color_record_proto_rawDesc), len(file_games_color_record_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_games_color_record_proto_goTypes,
		DependencyIndexes: file_games_color_record_proto_depIdxs,
		EnumInfos:         file_games_color_record_proto_enumTypes,
	}.Build()
	File_games_color_record_proto = out.File
	file_games_color_record_proto_goTypes = nil
	file_games_color_record_proto_depIdxs = nil
}
