# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cards/cards.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cards/cards.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61rds/cards.proto\x12\x02\x63\x63*f\n\x08\x43\x61rdType\x12\x19\n\x15\x43\x41RD_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03INT\x10\x01\x12\t\n\x05POKER\x10\x02\x12\x08\n\x04\x44ICE\x10\x03\x12\x0c\n\x08ROULETTE\x10\x04\x12\t\n\x05WHEEL\x10\x05\x12\x08\n\x04\x46LOW\x10\x06\x42z\n\x15\x63om.wecasino.proto.ccB\nCardsProtoP\x01Z-github.com/wecasino/wecasino-proto/pbgo/cards\xa2\x02\x03\x43XX\xaa\x02\x02\x43\x63\xca\x02\x02\x43\x63\xe2\x02\x0e\x43\x63\\GPBMetadata\xea\x02\x02\x43\x63\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cards.cards_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.wecasino.proto.ccB\nCardsProtoP\001Z-github.com/wecasino/wecasino-proto/pbgo/cards\242\002\003CXX\252\002\002Cc\312\002\002Cc\342\002\016Cc\\GPBMetadata\352\002\002Cc'
  _globals['_CARDTYPE']._serialized_start=25
  _globals['_CARDTYPE']._serialized_end=127
# @@protoc_insertion_point(module_scope)
