// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards/cards.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.cards;

public final class CardsProto {
  private CardsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cards/cards.proto\022\005cards*q\n\010CardType\022\031" +
      "\n\025CARD_TYPE_UNSPECIFIED\020\000\022\007\n\003INT\020\001\022\t\n\005PO" +
      "KER\020\002\022\010\n\004DICE\020\003\022\014\n\010ROULETTE\020\004\022\t\n\005WHEEL\020\005" +
      "\022\010\n\004FLOW\020\006\022\t\n\005COLOR\020\007B\211\001\n\030com.wecasino.p" +
      "roto.cardsB\nCardsProtoP\001Z-github.com/wec" +
      "asino/wecasino-proto/pbgo/cards\242\002\003CXX\252\002\005" +
      "Cards\312\002\005Cards\342\002\021Cards\\GPBMetadata\352\002\005Card" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
