// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards/dice.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.cards;

public final class DiceProto {
  private DiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020cards/dice.proto\022\005cards*m\n\010DiceCard\022\031\n" +
      "\025DICE_CARD_UNSPECIFIED\020\000\022\n\n\006DICE_1\020\001\022\n\n\006" +
      "DICE_2\020\002\022\n\n\006DICE_3\020\003\022\n\n\006DICE_4\020\004\022\n\n\006DICE" +
      "_5\020\005\022\n\n\006DICE_6\020\006B\210\001\n\030com.wecasino.proto." +
      "cardsB\tDiceProtoP\001Z-github.com/wecasino/" +
      "wecasino-proto/pbgo/cards\242\002\003CXX\252\002\005Cards\312" +
      "\002\005Cards\342\002\021Cards\\GPBMetadata\352\002\005Cardsb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
