// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards/sakla.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.cards;

public final class SaklaProto {
  private SaklaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cards/sakla.proto\022\005cards*\277\006\n\tSaklaCard" +
      "\022\032\n\026SAKLA_CARD_UNSPECIFIED\020\000\022\017\n\013SAKLA_AN" +
      "Y_A\020\001\022\017\n\013SAKLA_ANY_2\020\002\022\017\n\013SAKLA_ANY_3\020\003\022" +
      "\017\n\013SAKLA_ANY_4\020\004\022\017\n\013SAKLA_ANY_5\020\005\022\017\n\013SAK" +
      "LA_ANY_6\020\006\022\017\n\013SAKLA_ANY_7\020\007\022\020\n\014SAKLA_ANY" +
      "_10\020\n\022\017\n\013SAKLA_ANY_J\020\013\022\017\n\013SAKLA_ANY_Q\020\014\022" +
      "\016\n\nSAKLA_MASK\020\017\022\016\n\nSWORDS_ANY\020\020\022\014\n\010SWORD" +
      "S_A\020\021\022\014\n\010SWORDS_2\020\022\022\014\n\010SWORDS_3\020\023\022\014\n\010SWO" +
      "RDS_4\020\024\022\014\n\010SWORDS_5\020\025\022\014\n\010SWORDS_6\020\026\022\014\n\010S" +
      "WORDS_7\020\027\022\r\n\tSWORDS_10\020\032\022\014\n\010SWORDS_J\020\033\022\014" +
      "\n\010SWORDS_Q\020\034\022\014\n\010CUPS_ANY\020 \022\n\n\006CUPS_A\020!\022\n" +
      "\n\006CUPS_2\020\"\022\n\n\006CUPS_3\020#\022\n\n\006CUPS_4\020$\022\n\n\006CU" +
      "PS_5\020%\022\n\n\006CUPS_6\020&\022\n\n\006CUPS_7\020\'\022\013\n\007CUPS_1" +
      "0\020*\022\n\n\006CUPS_J\020+\022\n\n\006CUPS_Q\020,\022\r\n\tCLUBS_ANY" +
      "\0200\022\013\n\007CLUBS_A\0201\022\013\n\007CLUBS_2\0202\022\013\n\007CLUBS_3\020" +
      "3\022\013\n\007CLUBS_4\0204\022\013\n\007CLUBS_5\0205\022\013\n\007CLUBS_6\0206" +
      "\022\013\n\007CLUBS_7\0207\022\014\n\010CLUBS_10\020:\022\013\n\007CLUBS_J\020;" +
      "\022\013\n\007CLUBS_Q\020<\022\r\n\tCOINS_ANY\020@\022\013\n\007COINS_A\020" +
      "A\022\013\n\007COINS_2\020B\022\013\n\007COINS_3\020C\022\013\n\007COINS_4\020D" +
      "\022\013\n\007COINS_5\020E\022\013\n\007COINS_6\020F\022\013\n\007COINS_7\020G\022" +
      "\014\n\010COINS_10\020J\022\013\n\007COINS_J\020K\022\013\n\007COINS_Q\020L\022" +
      "\023\n\017SAKLA_SUIT_MASK\020pB\211\001\n\030com.wecasino.pr" +
      "oto.cardsB\nSaklaProtoP\001Z-github.com/weca" +
      "sino/wecasino-proto/pbgo/cards\242\002\003CXX\252\002\005C" +
      "ards\312\002\005Cards\342\002\021Cards\\GPBMetadata\352\002\005Cards" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
