// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards/wheel.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.cards;

/**
 * <pre>
 * empty Wheel
 * </pre>
 *
 * Protobuf enum {@code cards.Wheel}
 */
public enum Wheel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WHEEL_UNSPECIFIED = 0;</code>
   */
  WHEEL_UNSPECIFIED(0),
  /**
   * <pre>
   * 24格 1 倍
   * </pre>
   *
   * <code>WHEEL24X1 = 1;</code>
   */
  WHEEL24X1(1),
  /**
   * <pre>
   * 12格 3 倍
   * </pre>
   *
   * <code>WHEEL12X3 = 2;</code>
   */
  WHEEL12X3(2),
  /**
   * <pre>
   * 8格 5 倍
   * </pre>
   *
   * <code>WHEEL8X5 = 3;</code>
   */
  WHEEL8X5(3),
  /**
   * <pre>
   * 4格 10 倍
   * </pre>
   *
   * <code>WHEEL4X10 = 4;</code>
   */
  WHEEL4X10(4),
  /**
   * <pre>
   * 2格 20 倍
   * </pre>
   *
   * <code>WHEEL2X20 = 5;</code>
   */
  WHEEL2X20(5),
  /**
   * <pre>
   * 1格 45 倍
   * </pre>
   *
   * <code>WHEELAX45 = 6;</code>
   */
  WHEELAX45(6),
  /**
   * <pre>
   * 1格 45 倍
   * </pre>
   *
   * <code>WHEELBX45 = 7;</code>
   */
  WHEELBX45(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Wheel.class.getName());
  }
  /**
   * <code>WHEEL_UNSPECIFIED = 0;</code>
   */
  public static final int WHEEL_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 24格 1 倍
   * </pre>
   *
   * <code>WHEEL24X1 = 1;</code>
   */
  public static final int WHEEL24X1_VALUE = 1;
  /**
   * <pre>
   * 12格 3 倍
   * </pre>
   *
   * <code>WHEEL12X3 = 2;</code>
   */
  public static final int WHEEL12X3_VALUE = 2;
  /**
   * <pre>
   * 8格 5 倍
   * </pre>
   *
   * <code>WHEEL8X5 = 3;</code>
   */
  public static final int WHEEL8X5_VALUE = 3;
  /**
   * <pre>
   * 4格 10 倍
   * </pre>
   *
   * <code>WHEEL4X10 = 4;</code>
   */
  public static final int WHEEL4X10_VALUE = 4;
  /**
   * <pre>
   * 2格 20 倍
   * </pre>
   *
   * <code>WHEEL2X20 = 5;</code>
   */
  public static final int WHEEL2X20_VALUE = 5;
  /**
   * <pre>
   * 1格 45 倍
   * </pre>
   *
   * <code>WHEELAX45 = 6;</code>
   */
  public static final int WHEELAX45_VALUE = 6;
  /**
   * <pre>
   * 1格 45 倍
   * </pre>
   *
   * <code>WHEELBX45 = 7;</code>
   */
  public static final int WHEELBX45_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Wheel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Wheel forNumber(int value) {
    switch (value) {
      case 0: return WHEEL_UNSPECIFIED;
      case 1: return WHEEL24X1;
      case 2: return WHEEL12X3;
      case 3: return WHEEL8X5;
      case 4: return WHEEL4X10;
      case 5: return WHEEL2X20;
      case 6: return WHEELAX45;
      case 7: return WHEELBX45;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Wheel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Wheel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Wheel>() {
          public Wheel findValueByNumber(int number) {
            return Wheel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.wecasino.proto.cards.WheelProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Wheel[] VALUES = values();

  public static Wheel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Wheel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:cards.Wheel)
}

