// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: games/xocdia/record.proto

package xocdia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameSubtype int32

const (
	// 未指定
	GameSubtype_XOCDIA_TYPE_UNSPECIFIED GameSubtype = 0
	// 色碟
	GameSubtype_XOCDIA_CLASSIC GameSubtype = 1
)

// Enum value maps for GameSubtype.
var (
	GameSubtype_name = map[int32]string{
		0: "XOCDIA_TYPE_UNSPECIFIED",
		1: "XOCDIA_CLASSIC",
	}
	GameSubtype_value = map[string]int32{
		"XOCDIA_TYPE_UNSPECIFIED": 0,
		"XOCDIA_CLASSIC":          1,
	}
)

func (x GameSubtype) Enum() *GameSubtype {
	p := new(GameSubtype)
	*p = x
	return p
}

func (x GameSubtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSubtype) Descriptor() protoreflect.EnumDescriptor {
	return file_games_xocdia_record_proto_enumTypes[0].Descriptor()
}

func (GameSubtype) Type() protoreflect.EnumType {
	return &file_games_xocdia_record_proto_enumTypes[0]
}

func (x GameSubtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSubtype.Descriptor instead.
func (GameSubtype) EnumDescriptor() ([]byte, []int) {
	return file_games_xocdia_record_proto_rawDescGZIP(), []int{0}
}

// 步驟，依據遊戲供應商邏輯，不是每個步驟都會走到
type Step int32

const (
	// 未指定
	Step_STEP_UNSPECIFIED Step = 0
	// 本局開始
	Step_ROUND_START Step = 1
	// 本局完成
	Step_ROUND_FINISHED Step = 2
	// 本局取消
	Step_ROUND_CANCELED Step = 3
	// 開放下注
	Step_ROUND_BET Step = 4
	// 停止下注
	Step_NO_MORE_BET Step = 5
	// 擲色碟
	Step_THROW_DICE Step = 8
	// PITBOSS 修改骰點
	Step_PITBOSS_MODIFY_BOWL Step = 16
)

// Enum value maps for Step.
var (
	Step_name = map[int32]string{
		0:  "STEP_UNSPECIFIED",
		1:  "ROUND_START",
		2:  "ROUND_FINISHED",
		3:  "ROUND_CANCELED",
		4:  "ROUND_BET",
		5:  "NO_MORE_BET",
		8:  "THROW_DICE",
		16: "PITBOSS_MODIFY_BOWL",
	}
	Step_value = map[string]int32{
		"STEP_UNSPECIFIED":    0,
		"ROUND_START":         1,
		"ROUND_FINISHED":      2,
		"ROUND_CANCELED":      3,
		"ROUND_BET":           4,
		"NO_MORE_BET":         5,
		"THROW_DICE":          8,
		"PITBOSS_MODIFY_BOWL": 16,
	}
)

func (x Step) Enum() *Step {
	p := new(Step)
	*p = x
	return p
}

func (x Step) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Step) Descriptor() protoreflect.EnumDescriptor {
	return file_games_xocdia_record_proto_enumTypes[1].Descriptor()
}

func (Step) Type() protoreflect.EnumType {
	return &file_games_xocdia_record_proto_enumTypes[1]
}

func (x Step) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Step.Descriptor instead.
func (Step) EnumDescriptor() ([]byte, []int) {
	return file_games_xocdia_record_proto_rawDescGZIP(), []int{1}
}

var File_games_xocdia_record_proto protoreflect.FileDescriptor

const file_games_xocdia_record_proto_rawDesc = "" +
	"\n" +
	"\x19games/xocdia/record.proto\x12\fgames.xocdia*>\n" +
	"\vGameSubtype\x12\x1b\n" +
	"\x17XOCDIA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eXOCDIA_CLASSIC\x10\x01*\x9e\x01\n" +
	"\x04Step\x12\x14\n" +
	"\x10STEP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROUND_START\x10\x01\x12\x12\n" +
	"\x0eROUND_FINISHED\x10\x02\x12\x12\n" +
	"\x0eROUND_CANCELED\x10\x03\x12\r\n" +
	"\tROUND_BET\x10\x04\x12\x0f\n" +
	"\vNO_MORE_BET\x10\x05\x12\x0e\n" +
	"\n" +
	"THROW_DICE\x10\b\x12\x17\n" +
	"\x13PITBOSS_MODIFY_BOWL\x10\x10B\xb5\x01\n" +
	"\x1fcom.wecasino.proto.games.xocdiaB\vRecordProtoP\x01Z4github.com/wecasino/wecasino-proto/pbgo/games/xocdia\xa2\x02\x03GXX\xaa\x02\fGames.Xocdia\xca\x02\fGames\\Xocdia\xe2\x02\x18Games\\Xocdia\\GPBMetadata\xea\x02\rGames::Xocdiab\x06proto3"

var (
	file_games_xocdia_record_proto_rawDescOnce sync.Once
	file_games_xocdia_record_proto_rawDescData []byte
)

func file_games_xocdia_record_proto_rawDescGZIP() []byte {
	file_games_xocdia_record_proto_rawDescOnce.Do(func() {
		file_games_xocdia_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_games_xocdia_record_proto_rawDesc), len(file_games_xocdia_record_proto_rawDesc)))
	})
	return file_games_xocdia_record_proto_rawDescData
}

var file_games_xocdia_record_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_games_xocdia_record_proto_goTypes = []any{
	(GameSubtype)(0), // 0: games.xocdia.GameSubtype
	(Step)(0),        // 1: games.xocdia.Step
}
var file_games_xocdia_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_games_xocdia_record_proto_init() }
func file_games_xocdia_record_proto_init() {
	if File_games_xocdia_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_games_xocdia_record_proto_rawDesc), len(file_games_xocdia_record_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_games_xocdia_record_proto_goTypes,
		DependencyIndexes: file_games_xocdia_record_proto_depIdxs,
		EnumInfos:         file_games_xocdia_record_proto_enumTypes,
	}.Build()
	File_games_xocdia_record_proto = out.File
	file_games_xocdia_record_proto_goTypes = nil
	file_games_xocdia_record_proto_depIdxs = nil
}
