// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/colorjackpot/record.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.games.colorjackpot;

public final class RecordProto {
  private RecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037games/colorjackpot/record.proto\022\022games" +
      ".colorjackpot*<\n\013GameSubtype\022\032\n\026COLOR_TY" +
      "PE_UNSPECIFIED\020\000\022\021\n\rCOLOR_JACKPOT\020\001*\236\003\n\004" +
      "Step\022\024\n\020STEP_UNSPECIFIED\020\000\022\017\n\013ROUND_STAR" +
      "T\020\001\022\022\n\016ROUND_FINISHED\020\002\022\022\n\016ROUND_CANCELE" +
      "D\020\003\022\r\n\tROUND_BET\020\004\022\017\n\013NO_MORE_BET\020\005\022\017\n\013T" +
      "HROW_COLOR\020\010\022\033\n\027LUCKY_WHEEL_ROUND_READY\020" +
      "\t\022\033\n\027LUCKY_WHEEL_ROUND_START\020\n\022\031\n\025LUCKY_" +
      "WHEEL_ROUND_BET\020\013\022\033\n\027LUCKY_WHEEL_NO_MORE" +
      "_BET\020\014\022\033\n\027LUCKY_WHEEL_THROW_WHEEL\020\r\022\025\n\021B" +
      "INGO_ROUND_READY\020\024\022\025\n\021BINGO_ROUND_START\020" +
      "\025\022\023\n\017BINGO_ROUND_BET\020\026\022\025\n\021BINGO_NO_MORE_" +
      "BET\020\027\022\024\n\020BINGO_THROW_BALL\020\030\022\027\n\023PITBOSS_M" +
      "ODIFY_BOWL\020\020*U\n\014ResourceType\022\035\n\031RESOURCE" +
      "_TYPE_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\017\n\013LUCKY" +
      "_WHEEL\020\002\022\t\n\005BINGO\020\003B\331\001\n%com.wecasino.pro" +
      "to.games.colorjackpotB\013RecordProtoP\001Z:gi" +
      "thub.com/wecasino/wecasino-proto/pbgo/ga" +
      "mes/colorjackpot\242\002\003GCX\252\002\022Games.Colorjack" +
      "pot\312\002\022Games\\Colorjackpot\342\002\036Games\\Colorja" +
      "ckpot\\GPBMetadata\352\002\023Games::Colorjackpotb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
