// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cards/coin.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coin int32

const (
	// 未指定
	Coin_COIN_CARD_UNSPECIFIED Coin = 0
	// 正面
	Coin_COIN_HEADS Coin = 1
	// 反面
	Coin_COIN_TAILS Coin = 2
)

// Enum value maps for Coin.
var (
	Coin_name = map[int32]string{
		0: "COIN_CARD_UNSPECIFIED",
		1: "COIN_HEADS",
		2: "COIN_TAILS",
	}
	Coin_value = map[string]int32{
		"COIN_CARD_UNSPECIFIED": 0,
		"COIN_HEADS":            1,
		"COIN_TAILS":            2,
	}
)

func (x Coin) Enum() *Coin {
	p := new(Coin)
	*p = x
	return p
}

func (x Coin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Coin) Descriptor() protoreflect.EnumDescriptor {
	return file_cards_coin_proto_enumTypes[0].Descriptor()
}

func (Coin) Type() protoreflect.EnumType {
	return &file_cards_coin_proto_enumTypes[0]
}

func (x Coin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Coin.Descriptor instead.
func (Coin) EnumDescriptor() ([]byte, []int) {
	return file_cards_coin_proto_rawDescGZIP(), []int{0}
}

var File_cards_coin_proto protoreflect.FileDescriptor

const file_cards_coin_proto_rawDesc = "" +
	"\n" +
	"\x10cards/coin.proto\x12\x05cards*A\n" +
	"\x04Coin\x12\x19\n" +
	"\x15COIN_CARD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"COIN_HEADS\x10\x01\x12\x0e\n" +
	"\n" +
	"COIN_TAILS\x10\x02B\x88\x01\n" +
	"\x18com.wecasino.proto.cardsB\tCoinProtoP\x01Z-github.com/wecasino/wecasino-proto/pbgo/cards\xa2\x02\x03CXX\xaa\x02\x05Cards\xca\x02\x05Cards\xe2\x02\x11Cards\\GPBMetadata\xea\x02\x05Cardsb\x06proto3"

var (
	file_cards_coin_proto_rawDescOnce sync.Once
	file_cards_coin_proto_rawDescData []byte
)

func file_cards_coin_proto_rawDescGZIP() []byte {
	file_cards_coin_proto_rawDescOnce.Do(func() {
		file_cards_coin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cards_coin_proto_rawDesc), len(file_cards_coin_proto_rawDesc)))
	})
	return file_cards_coin_proto_rawDescData
}

var file_cards_coin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cards_coin_proto_goTypes = []any{
	(Coin)(0), // 0: cards.Coin
}
var file_cards_coin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cards_coin_proto_init() }
func file_cards_coin_proto_init() {
	if File_cards_coin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cards_coin_proto_rawDesc), len(file_cards_coin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cards_coin_proto_goTypes,
		DependencyIndexes: file_cards_coin_proto_depIdxs,
		EnumInfos:         file_cards_coin_proto_enumTypes,
	}.Build()
	File_cards_coin_proto = out.File
	file_cards_coin_proto_goTypes = nil
	file_cards_coin_proto_depIdxs = nil
}
