// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: cards/dice.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiceCard int32

const (
	// 未指定
	DiceCard_DICE_CARD_UNSPECIFIED DiceCard = 0
	DiceCard_DICE_1                DiceCard = 1
	DiceCard_DICE_2                DiceCard = 2
	DiceCard_DICE_3                DiceCard = 3
	DiceCard_DICE_4                DiceCard = 4
	DiceCard_DICE_5                DiceCard = 5
	DiceCard_DICE_6                DiceCard = 6
)

// Enum value maps for DiceCard.
var (
	DiceCard_name = map[int32]string{
		0: "DICE_CARD_UNSPECIFIED",
		1: "DICE_1",
		2: "DICE_2",
		3: "DICE_3",
		4: "DICE_4",
		5: "DICE_5",
		6: "DICE_6",
	}
	DiceCard_value = map[string]int32{
		"DICE_CARD_UNSPECIFIED": 0,
		"DICE_1":                1,
		"DICE_2":                2,
		"DICE_3":                3,
		"DICE_4":                4,
		"DICE_5":                5,
		"DICE_6":                6,
	}
)

func (x DiceCard) Enum() *DiceCard {
	p := new(DiceCard)
	*p = x
	return p
}

func (x DiceCard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiceCard) Descriptor() protoreflect.EnumDescriptor {
	return file_cards_dice_proto_enumTypes[0].Descriptor()
}

func (DiceCard) Type() protoreflect.EnumType {
	return &file_cards_dice_proto_enumTypes[0]
}

func (x DiceCard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiceCard.Descriptor instead.
func (DiceCard) EnumDescriptor() ([]byte, []int) {
	return file_cards_dice_proto_rawDescGZIP(), []int{0}
}

var File_cards_dice_proto protoreflect.FileDescriptor

const file_cards_dice_proto_rawDesc = "" +
	"\n" +
	"\x10cards/dice.proto\x12\x05cards*m\n" +
	"\bDiceCard\x12\x19\n" +
	"\x15DICE_CARD_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DICE_1\x10\x01\x12\n" +
	"\n" +
	"\x06DICE_2\x10\x02\x12\n" +
	"\n" +
	"\x06DICE_3\x10\x03\x12\n" +
	"\n" +
	"\x06DICE_4\x10\x04\x12\n" +
	"\n" +
	"\x06DICE_5\x10\x05\x12\n" +
	"\n" +
	"\x06DICE_6\x10\x06B\x88\x01\n" +
	"\x18com.wecasino.proto.cardsB\tDiceProtoP\x01Z-github.com/wecasino/wecasino-proto/pbgo/cards\xa2\x02\x03CXX\xaa\x02\x05Cards\xca\x02\x05Cards\xe2\x02\x11Cards\\GPBMetadata\xea\x02\x05Cardsb\x06proto3"

var (
	file_cards_dice_proto_rawDescOnce sync.Once
	file_cards_dice_proto_rawDescData []byte
)

func file_cards_dice_proto_rawDescGZIP() []byte {
	file_cards_dice_proto_rawDescOnce.Do(func() {
		file_cards_dice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cards_dice_proto_rawDesc), len(file_cards_dice_proto_rawDesc)))
	})
	return file_cards_dice_proto_rawDescData
}

var file_cards_dice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cards_dice_proto_goTypes = []any{
	(DiceCard)(0), // 0: cards.DiceCard
}
var file_cards_dice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cards_dice_proto_init() }
func file_cards_dice_proto_init() {
	if File_cards_dice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cards_dice_proto_rawDesc), len(file_cards_dice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cards_dice_proto_goTypes,
		DependencyIndexes: file_cards_dice_proto_depIdxs,
		EnumInfos:         file_cards_dice_proto_enumTypes,
	}.Build()
	File_cards_dice_proto = out.File
	file_cards_dice_proto_goTypes = nil
	file_cards_dice_proto_depIdxs = nil
}
