// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/oneluckynight/record.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.games.oneluckynight;

public final class RecordProto {
  private RecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n games/oneluckynight/record.proto\022\023game" +
      "s.oneluckynight*L\n\013GameSubtype\022\"\n\036ONELUC" +
      "KYNIGHT_TYPE_UNSPECIFIED\020\000\022\031\n\025ONELUCKYNI" +
      "GHT_CLASSIC\020\001*D\n\014ResourceType\022\035\n\031RESOURC" +
      "E_TYPE_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\t\n\005EXTR" +
      "A\020\002*\310\002\n\004Step\022\024\n\020STEP_UNSPECIFIED\020\000\022\017\n\013RO" +
      "UND_START\020\001\022\022\n\016ROUND_FINISHED\020\002\022\023\n\017SHOW_" +
      "FIRST_CARD\020\003\022\r\n\tROUND_BET\020\010\022\017\n\013NO_MORE_B" +
      "ET\020\t\022\017\n\013SHOW_NORMAL\020\013\022\017\n\013SHOW_BANKER\020\014\022\017" +
      "\n\013SHOW_PLAYER\020\r\022\025\n\021DEAL_PLAYER_EXTRA\020\020\022\025" +
      "\n\021DEAL_BANKER_EXTRA\020\024\022\022\n\016DEALER_CONFIRM\020" +
      "\027\022\031\n\025PITBOSS_MODIFY_NORMAL\020\030\022\037\n\033PITBOSS_" +
      "MODIFY_PLAYER_EXTRA\020\031\022\037\n\033PITBOSS_MODIFY_" +
      "BANKER_EXTRA\020\032*8\n\010GameSeat\022\024\n\020SEAT_UNSPE" +
      "CIFIED\020\000\022\n\n\006PLAYER\020\002\022\n\n\006BANKER\020\003B\337\001\n&com" +
      ".wecasino.proto.games.oneluckynightB\013Rec" +
      "ordProtoP\001Z;github.com/wecasino/wecasino" +
      "-proto/pbgo/games/oneluckynight\242\002\003GOX\252\002\023" +
      "Games.Oneluckynight\312\002\023Games\\Oneluckynigh" +
      "t\342\002\037Games\\Oneluckynight\\GPBMetadata\352\002\024Ga" +
      "mes::Oneluckynightb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
