// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/threecards/record.proto

// Protobuf Java Version: 4.26.1
package com.wecasino.proto.games.threecards;

/**
 * <pre>
 * 豹子 &gt; 同花順 &gt; 同花 &gt; 順子 &gt; 對子 &gt; 散牌
 * </pre>
 *
 * Protobuf enum {@code games.threecards.CardStyle}
 */
public enum CardStyle
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 散牌
   * </pre>
   *
   * <code>NONE = 0;</code>
   */
  NONE(0),
  /**
   * <pre>
   * 對子
   * </pre>
   *
   * <code>PAIR = 1;</code>
   */
  PAIR(1),
  /**
   * <pre>
   * 順子
   * </pre>
   *
   * <code>STRAIGHT = 2;</code>
   */
  STRAIGHT(2),
  /**
   * <pre>
   * 同花
   * </pre>
   *
   * <code>FLUSH = 3;</code>
   */
  FLUSH(3),
  /**
   * <pre>
   * 順子
   * </pre>
   *
   * <code>STRAIGHTF = 4;</code>
   */
  STRAIGHTF(4),
  /**
   * <pre>
   * 豹子
   * </pre>
   *
   * <code>LEOPARD = 5;</code>
   */
  LEOPARD(5),
  /**
   * <pre>
   * 豹子殺手
   * </pre>
   *
   * <code>LEOPARD_KILLER = 6;</code>
   */
  LEOPARD_KILLER(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      CardStyle.class.getName());
  }
  /**
   * <pre>
   * 散牌
   * </pre>
   *
   * <code>NONE = 0;</code>
   */
  public static final int NONE_VALUE = 0;
  /**
   * <pre>
   * 對子
   * </pre>
   *
   * <code>PAIR = 1;</code>
   */
  public static final int PAIR_VALUE = 1;
  /**
   * <pre>
   * 順子
   * </pre>
   *
   * <code>STRAIGHT = 2;</code>
   */
  public static final int STRAIGHT_VALUE = 2;
  /**
   * <pre>
   * 同花
   * </pre>
   *
   * <code>FLUSH = 3;</code>
   */
  public static final int FLUSH_VALUE = 3;
  /**
   * <pre>
   * 順子
   * </pre>
   *
   * <code>STRAIGHTF = 4;</code>
   */
  public static final int STRAIGHTF_VALUE = 4;
  /**
   * <pre>
   * 豹子
   * </pre>
   *
   * <code>LEOPARD = 5;</code>
   */
  public static final int LEOPARD_VALUE = 5;
  /**
   * <pre>
   * 豹子殺手
   * </pre>
   *
   * <code>LEOPARD_KILLER = 6;</code>
   */
  public static final int LEOPARD_KILLER_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CardStyle valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CardStyle forNumber(int value) {
    switch (value) {
      case 0: return NONE;
      case 1: return PAIR;
      case 2: return STRAIGHT;
      case 3: return FLUSH;
      case 4: return STRAIGHTF;
      case 5: return LEOPARD;
      case 6: return LEOPARD_KILLER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CardStyle>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CardStyle> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CardStyle>() {
          public CardStyle findValueByNumber(int number) {
            return CardStyle.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.wecasino.proto.games.threecards.RecordProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final CardStyle[] VALUES = values();

  public static CardStyle valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CardStyle(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:games.threecards.CardStyle)
}

