// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/games.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.games;

public final class GamesProto {
  private GamesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021games/games.proto\022\005games*\337\002\n\010GameType\022" +
      "\031\n\025GAME_TYPE_UNSPECIFIED\020\000\022\014\n\010BACCARAT\020\020" +
      "\022\r\n\tBACCARAT2\0202\022\r\n\tBACCARAT3\0203\022\020\n\014THEBIG" +
      "BATTLE\020\021\022\016\n\nTHREECARDS\020\022\022\r\n\tBULLFIGHT\020\023\022" +
      "\n\n\006FANTAN\020\024\022\t\n\005SICBO\020 \022\r\n\tCOLORGAME\020!\022\014\n" +
      "\010DROPBALL\020\"\022\014\n\010ROULETTE\020$\022\016\n\nLUCKYWHEEL\020" +
      "(\022\n\n\006XOCDIA\020)\022\025\n\021COLORGAME_JACKPOT\020*\022\020\n\014" +
      "ONELUCKYNINE\020+\022\010\n\004HILO\020,\022\t\n\005SAKLA\020-\022\014\n\010C" +
      "ARACRUZ\020.\022\020\n\014BACCARATSTEP\020/\022\t\n\005BACBO\0200\022\024" +
      "\n\020BACCARATANGLEEYE\0204*\254\002\n\010FlowSeat\022\024\n\020SEA" +
      "T_UNSPECIFIED\020\000\022\014\n\010DEALER_A\0202\022\025\n\021PREVIOU" +
      "S_DEALER_A\0203\022\014\n\010DEALER_B\0204\022\025\n\021PREVIOUS_D" +
      "EALER_B\0205\022\014\n\010DEALER_C\0206\022\025\n\021PREVIOUS_DEAL" +
      "ER_C\0207\022\n\n\006DEALER\020@\022\023\n\017PREVIOUS_DEALER\020A\022" +
      "\013\n\007PITBOSS\020B\022\024\n\020PREVIOUS_PITBOSS\020C\022\n\n\006PL" +
      "AYER\020D\022\n\n\006BANKER\020E\022\010\n\004LEFT\020F\022\t\n\005RIGHT\020G\022" +
      "\013\n\007JACKPOT\020H\022\013\n\007CONTROL\020`\022\020\n\014INSTRUCTION" +
      "S\020c*\215\001\n\014ResourceType\022\035\n\031RESOURCE_TYPE_UN" +
      "SPECIFIED\020\000\022\010\n\004SHOE\020@\022\010\n\004HAND\020A\022\t\n\005FIELD" +
      "\020B\022\016\n\nFIRST_CARD\020C\022\014\n\010SHOE_CUT\020D\022\013\n\007DISC" +
      "ARD\020E\022\024\n\020JACKPOT_RESOURCE\020F*?\n\007WinType\022\030" +
      "\n\024WIN_TYPE_UNSPECIFIED\020\000\022\010\n\004LOSE\020\001\022\007\n\003WI" +
      "N\020\002\022\007\n\003TIE\020\003B\211\001\n\030com.wecasino.proto.game" +
      "sB\nGamesProtoP\001Z-github.com/wecasino/wec" +
      "asino-proto/pbgo/games\242\002\003GXX\252\002\005Games\312\002\005G" +
      "ames\342\002\021Games\\GPBMetadata\352\002\005Gamesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
