# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: games/threecards/record.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'games/threecards/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgames/threecards/record.proto\x12\x10games.threecards*a\n\x0bGameSubtype\x12\x1f\n\x1bTHREECARDS_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12THREECARDS_CLASSIC\x10\x01\x12\x19\n\x15THREECARDS_BLOCKCHAIN\x10\x10*\xd5\x02\n\x04Step\x12\x14\n\x10STEP_UNSPECIFIED\x10\x00\x12\x0f\n\x0bROUND_START\x10\x01\x12\x12\n\x0eROUND_FINISHED\x10\x02\x12\x12\n\x0eROUND_CANCELED\x10\x03\x12\x0f\n\x0b\x44\x45\x41L_LEFT_1\x10\x04\x12\x10\n\x0c\x44\x45\x41L_RIGHT_1\x10\x05\x12\x0f\n\x0b\x44\x45\x41L_LEFT_2\x10\x06\x12\x10\n\x0c\x44\x45\x41L_RIGHT_2\x10\x07\x12\x0f\n\x0b\x44\x45\x41L_LEFT_3\x10\x08\x12\x10\n\x0c\x44\x45\x41L_RIGHT_3\x10\t\x12\r\n\tROUND_BET\x10\x0c\x12\x0f\n\x0bNO_MORE_BET\x10\r\x12\x10\n\x0cSHOW_LEFT_12\x10\x10\x12\x11\n\rSHOW_RIGHT_12\x10\x11\x12\x0f\n\x0bSHOW_LEFT_3\x10\x12\x12\x10\n\x0cSHOW_RIGHT_3\x10\x13\x12\x12\n\x0e\x44\x45\x41LER_CONFIRM\x10\x14\x12\x19\n\x15PITBOSS_MODIFY_NORMAL\x10\x18*\x8d\x01\n\x0b\x43\x61rdPattern\x12\x1c\n\x18\x43\x41RD_PATTERN_UNSPECIFIED\x10\x00\x12\x08\n\x04HIGH\x10\x01\x12\x08\n\x04PAIR\x10\x02\x12\x0c\n\x08STRAIGHT\x10\x03\x12\t\n\x05\x46LUSH\x10\x04\x12\x12\n\x0eSTRAIGHT_FLUSH\x10\x05\x12\x0b\n\x07LEOPARD\x10\x06\x12\x12\n\x0eLEOPARD_KILLER\x10\x07\x42\xcd\x01\n#com.wecasino.proto.games.threecardsB\x0bRecordProtoP\x01Z8github.com/wecasino/wecasino-proto/pbgo/games/threecards\xa2\x02\x03GTX\xaa\x02\x10Games.Threecards\xca\x02\x10Games\\Threecards\xe2\x02\x1cGames\\Threecards\\GPBMetadata\xea\x02\x11Games::Threecardsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'games.threecards.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.wecasino.proto.games.threecardsB\013RecordProtoP\001Z8github.com/wecasino/wecasino-proto/pbgo/games/threecards\242\002\003GTX\252\002\020Games.Threecards\312\002\020Games\\Threecards\342\002\034Games\\Threecards\\GPBMetadata\352\002\021Games::Threecards'
  _globals['_GAMESUBTYPE']._serialized_start=51
  _globals['_GAMESUBTYPE']._serialized_end=148
  _globals['_STEP']._serialized_start=151
  _globals['_STEP']._serialized_end=492
  _globals['_CARDPATTERN']._serialized_start=495
  _globals['_CARDPATTERN']._serialized_end=636
# @@protoc_insertion_point(module_scope)
