// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/baccarat2/record.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.games.baccarat2;

public final class RecordProto {
  private RecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034games/baccarat2/record.proto\022\017games.ba" +
      "ccarat2*\357\001\n\013GameSubtype\022\035\n\031BACCARAT_TYPE" +
      "_UNSPECIFIED\020\000\022\024\n\020BACCARAT_CLASSIC\020\001\022\030\n\024" +
      "BACCARAT_TRADITIONAL\020\002\022\022\n\016BACCARAT_SPEED" +
      "\020\003\022\021\n\rBACCARAT_PEEK\020\010\022\024\n\020BACCARAT_FORTUN" +
      "E\020\014\022\027\n\023BACCARAT_BLOCKCHAIN\020\020\022\035\n\031BACCARAT" +
      "_SPEED_BLOCKCHAIN\020\022\022\034\n\030BACCARAT_PEEK_BLO" +
      "CKCHAIN\020\030*D\n\014ResourceType\022\035\n\031RESOURCE_TY" +
      "PE_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\t\n\005EXTRA\020\002*" +
      "\367\004\n\004Step\022\024\n\020STEP_UNSPECIFIED\020\000\022\017\n\013ROUND_" +
      "START\020\001\022\022\n\016ROUND_FINISHED\020\002\022\023\n\017SHOW_FIRS" +
      "T_CARD\020\003\022\021\n\rDEAL_PLAYER_1\020\004\022\021\n\rDEAL_BANK" +
      "ER_1\020\005\022\021\n\rDEAL_PLAYER_2\020\006\022\021\n\rDEAL_BANKER" +
      "_2\020\007\022\r\n\tROUND_BET\020\010\022\017\n\013NO_MORE_BET\020\t\022\017\n\013" +
      "SHOW_NORMAL\020\013\022\017\n\013SHOW_BANKER\020\014\022\017\n\013SHOW_P" +
      "LAYER\020\r\022\021\n\rSHOW_BANKER_1\020\036\022\021\n\rSHOW_BANKE" +
      "R_2\020\037\022\021\n\rSHOW_PLAYER_1\020!\022\021\n\rSHOW_PLAYER_" +
      "2\020\"\022\017\n\013PEEK_NORMAL\020\016\022\024\n\020PEEK_SHOW_NORMAL" +
      "\020\017\022\025\n\021DEAL_PLAYER_EXTRA\020\020\022\032\n\026PEEK_DEAL_P" +
      "LAYER_EXTRA\020\021\022\032\n\026PEEK_SHOW_PLAYER_EXTRA\020" +
      "\022\022\025\n\021DEAL_BANKER_EXTRA\020\024\022\032\n\026PEEK_DEAL_BA" +
      "NKER_EXTRA\020\025\022\032\n\026PEEK_SHOW_BANKER_EXTRA\020\026" +
      "\022\022\n\016DEALER_CONFIRM\020\027\022\031\n\025PITBOSS_MODIFY_N" +
      "ORMAL\020\030\022\037\n\033PITBOSS_MODIFY_PLAYER_EXTRA\020\031" +
      "\022\037\n\033PITBOSS_MODIFY_BANKER_EXTRA\020\032*8\n\010Gam" +
      "eSeat\022\024\n\020SEAT_UNSPECIFIED\020\000\022\n\n\006PLAYER\020\002\022" +
      "\n\n\006BANKER\020\003B\307\001\n\"com.wecasino.proto.games" +
      ".baccarat2B\013RecordProtoP\001Z7github.com/we" +
      "casino/wecasino-proto/pbgo/games/baccara" +
      "t2\242\002\003GBX\252\002\017Games.Baccarat2\312\002\017Games\\Bacca" +
      "rat2\342\002\033Games\\Baccarat2\\GPBMetadata\352\002\020Gam" +
      "es::Baccarat2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
