// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games/baccaratrenovate/record.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.games.baccaratrenovate;

public final class RecordProto {
  private RecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#games/baccaratrenovate/record.proto\022\026g" +
      "ames.baccaratrenovate*A\n\013GameSubtype\022\035\n\031" +
      "BACCARAT_TYPE_UNSPECIFIED\020\000\022\023\n\017BACCARAT_" +
      "INPLAY\020\001*D\n\014ResourceType\022\035\n\031RESOURCE_TYP" +
      "E_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\t\n\005EXTRA\020\002*\326" +
      "\004\n\004Step\022\024\n\020STEP_UNSPECIFIED\020\000\022\017\n\013ROUND_S" +
      "TART\020\001\022\022\n\016ROUND_FINISHED\020\002\022\023\n\017SHOW_FIRST" +
      "_CARD\020\003\022\021\n\rDEAL_PLAYER_1\020\004\022\021\n\rDEAL_BANKE" +
      "R_1\020\005\022\021\n\rDEAL_PLAYER_2\020\006\022\021\n\rDEAL_BANKER_" +
      "2\020\007\022\r\n\tROUND_BET\020\010\022\017\n\013NO_MORE_BET\020\t\022\017\n\013S" +
      "HOW_NORMAL\020\013\022\r\n\tSHOW_LEFT\020\014\022\021\n\rSHOW_BANK" +
      "ER_1\020\036\022\021\n\rSHOW_BANKER_2\020\037\022\021\n\rSHOW_PLAYER" +
      "_1\020!\022\021\n\rSHOW_PLAYER_2\020\"\022\025\n\021DEAL_PLAYER_E" +
      "XTRA\020\020\022\025\n\021DEAL_BANKER_EXTRA\020\024\022\022\n\016DEALER_" +
      "CONFIRM\020\027\022\031\n\025PITBOSS_MODIFY_NORMAL\020\030\022\037\n\033" +
      "PITBOSS_MODIFY_PLAYER_EXTRA\020\031\022\037\n\033PITBOSS" +
      "_MODIFY_BANKER_EXTRA\020\032\022\026\n\022SECOND_ROUND_S" +
      "TART\020\'\022\024\n\020SECOND_ROUND_BET\020(\022\026\n\022SECOND_N" +
      "O_MORE_BET\020)\022\025\n\021THIRD_ROUND_START\020*\022\023\n\017T" +
      "HIRD_ROUND_BET\020+\022\025\n\021THIRD_NO_MORE_BET\020,*" +
      "8\n\010GameSeat\022\024\n\020SEAT_UNSPECIFIED\020\000\022\n\n\006PLA" +
      "YER\020\002\022\n\n\006BANKER\020\003B\361\001\n)com.wecasino.proto" +
      ".games.baccaratrenovateB\013RecordProtoP\001Z>" +
      "github.com/wecasino/wecasino-proto/pbgo/" +
      "games/baccaratrenovate\242\002\003GBX\252\002\026Games.Bac" +
      "caratrenovate\312\002\026Games\\Baccaratrenovate\342\002" +
      "\"Games\\Baccaratrenovate\\GPBMetadata\352\002\027Ga" +
      "mes::Baccaratrenovateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
